### ISSUE TITLE
mlr3proba abstraction to 2-3 packages?

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#100]
Bit back and forth here, which is far from ideal. But given the number of learners and measures and perhaps it not being clear to users which tasks lie where, should `mlr3proba` be split into smaller packages?

I see two options if yes:

1. `mlr3survival` - Survival only
2. `mlr3density` - Density estimation only
3. `mlr3probregr` - Probabilistic regression only

Or:

We keep 1. and 2. but instead of a package for probabilistic regression we instead add `distr` as a return type for `TaskRegr` in `mlr3` and then add learners to `mlr3learners.<package>` and measures to `mlr3measures`.

______

Advantages:
* Relatively few downloads so now isn't a bad time to do this
* More packages = more visibility
* Makes it clearer what each package is for and this may be preferred especially for a lot of users who will only ever use density and survival
* Will make each package cleaner

Disadvantages:
* Quite a big change, so could cause problems with any current users
* Makes it *slightly* more complicated to use transformers/pipelines between survival and probabilistic regression
* Prob regr may be buried in `mlr3` and never used or people never aware

**Comment by RaphaelS1** [comment]
I think this being issue 100 is very fitting.

**Comment by fkiraly** [comment]
sounds a bit complex in terms of dependencies - why would this not introduce cirular ones given common reduction strategies?

**Comment by RaphaelS1** [comment]
Well none are dependent on each other.
A reduction strategy may look like:

`mlr3survival -> mlr3pipelines -> mlr3probregr -> pipelines -> survival`

But this is no different than any other pipeline converting one task to another. This is not a circular dependency as one package does not *depend* on the other.

**Comment by fkiraly** [comment]
So which package/module would reduction strategies survival->regression or regression->survival sit in?
Maybe a very general question too, since doesn´t every reduction strategy have an explicit dependency on the two tasks (the objects), the one reduced from and the one reduced to?

**Comment by RaphaelS1** [comment]
Well that comes down to if we can put it in `mlr3pipelines`. If we can then all a user needs to do is load the two packages containing the two different tasks, as well as pipelines. Otherwise it doesn't really matter as long as we make it clear. To me it is sensible to keep the reduction with the task it is solving, i.e. surv -> regr lives in survival as this solves a survival task.

**Comment by fkiraly** [comment]
So you would put all reduction in mlr3pipelines, no matter if it reduces from module A to module B, which the standard user might not ever use?
What about the alternative to put reductions from module A methods to module B methods in module A? With a "lazy" dependency on mlr3pipelines?

**Comment by RaphaelS1** [comment]
Sure that was the second option I suggested, and pipelines is already a "suggest" so this is covered

**Comment by fkiraly** [comment]
Makes sense.

**Comment by adibender** [comment]
I guess this should be decided before submitting manuscripts

**Comment by RaphaelS1** [comment]
I'd thought about that too and I think we should not do this but keep as-is. Whilst I agree it would initially be easier for people who want survival to find mlr3survival, and similarly for density; I think the advantages of keeping this all in one package (interfacing distr6 cleanly; transformations between each other; same return types), outweighs the abstraction advantage. Also first para of paper claims that the current structure is actually an advantage
