### ISSUE TITLE
Move vignettes to mlr3book

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#102]
* [x] Survival - https://github.com/mlr-org/mlr3book/pull/163
* [x] Density - https://github.com/mlr-org/mlr3book/pull/165

**Comment by RaphaelS1** [comment]
Waiting for  to https://github.com/mlr-org/mlr3book/pull/184 to be closed

**Comment by mllg** [comment]
You can close here, I guess.
