### ISSUE TITLE
Add examples to mlr3gallery

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#103]
* [ ] survival
* [ ] density

**Comment by RaphaelS1** [comment]
@adibender any update on the survival gallery post?

**Comment by adibender** [comment]
give me one or two more weeks. Semester is about to end

**Comment by adibender** [comment]
A first draft is [here](https://github.com/mlr-org/mlr3gallery/pull/92) but need to wait for speed bottleneck fix

**Comment by adibender** [comment]
@RaphaelS1 Is the bottleneck fixed yet?

**Comment by RaphaelS1** [comment]
@adibender nope
