### ISSUE TITLE
autoplot fitted model

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#107]
Idea is to add some visualisation for a fitted model. This involves

1. Creating a function to  generate a grid of new covariate data (or allowing user to input their own grid)
2. Making predictions on this new data
3. Plotting predictions with `distr6` - note that plotting currently exists in distr6, `autoplot` can call `plot` on the predicted `VectorDistribution`. I will write a `plot` function in `distr6` for these to make it easier.

**Comment by RaphaelS1** [comment]
I've now added plotting for `VectorDistribution`s in the master branch of `distr6`, so if you install from `remotes` this will make step 3. easier

**Comment by adibender** [comment]
so the interface would be something like 

`autoplot(lrnr, newdata, type = "survival")`? 

The `autopot` version in **`mlr3viz`** are S3 methods that dispatch w.r.t. to the class of the object, while we would need something that recognizes that its a `LearnerSurv` right?

**Comment by RaphaelS1** [comment]
right, but dispatch works on R6 so `autoplot.LearnerSurv` will work

**Comment by RaphaelS1** [comment]
although to be more consistent with `mlr3` interface it might be better to have

```R
autoplot(lrnr, task, type = "survival")
```
