### ISSUE TITLE
learner$predict_newdata not working for surv learners

### ISSUE THREAD

**Issue by adibender** [mlr-org/mlr3proba#109]
``` r
library(mlr3)
library(mlr3proba)

## classification
task <- mlr3::tsk("iris")
lrnr <- mlr_learners$get("classif.rpart")

lrnr$train(task, row_ids = 1:100)
ndf <- pammtools::make_newdata(task$data(), Species = unique(Species))
pred <- lrnr$predict_newdata(newdata = ndf)
pred
#> <PredictionClassif> for 3 observations:
#>  row_id      truth   response
#>       1     setosa versicolor
#>       2 versicolor versicolor
#>       3  virginica versicolor

## survival
task <- mlr3::tsk("rats")
lrnr <- mlr_learners$get("surv.coxph")
lrnr$train(task)

ndf <- pammtools::make_newdata(task$data(), sex = unique(sex))
ndf
#>    time status litter        rx sex
#> 1 90.44  FALSE   50.5 0.3333333   f
#> 2 90.44  FALSE   50.5 0.3333333   m
pred <- lrnr$predict_newdata(newdata = ndf)
#> Error in fun(value, id, type, levels): object 'vale' not found
```

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

related to #107

**Comment by RaphaelS1** [comment]
I didn't even know this method exactly, I assume it's just a helper to use a dataframe instead of a `task`? Anyway the error is clearly due then to this not being overloaded in `LearnerSurv`. Do you want to do it?

**Comment by RaphaelS1** [comment]
Actually I did some more digging and I think it may actually be line 20: https://github.com/mlr-org/mlr3/blob/master/R/auto_convert.R

Would you mind checking this and putting in a PR?

**Comment by adibender** [comment]
sure, will do later

**Comment by adibender** [comment]
I also see, that my `make_newdata` function is not very robust, e.g., converts logical to character and makes integer -> numeric oO

**Comment by adibender** [comment]
The PR in mlr3 is merged, so I think this can be closed
