### ISSUE TITLE
MeasureSurvAUC uses grepl on id for dispatch

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3proba#125]
https://github.com/mlr-org/mlr3proba/blob/4264648de7729176415f7b7ef0de227c1ccca745/R/MeasureSurvAUC.R#L55

Derived measures break if I rename them.

**Comment by RaphaelS1** [comment]
All the survAUC measures are going to be remade within proba soon, for now I'm happy to add some hacky lookup and then fix this when I fix the measures

**Comment by RaphaelS1** [comment]
on hold until https://github.com/mlr-org/mlr3proba/pull/133 closed
