### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3proba#126]
I'm not super happy with the naming scheme for ids or dictionary keys, they sometimes really look odd. However, we should at least try being consistent. Would you consider renaming ids and dictionary keys to underscore style instead of lowerCamelCase?

**Comment by RaphaelS1** [comment]
I am also not super happy with it. A big problem is the various c-indices, but these are all being combined in a near-future update. The other problem is standard errors, I agree underscore will look better, e.g. `logloss_se`. A general better naming scheme would be the unique ID then the class, e.g. `uno_tpr`, `uno_tnr`.

**Comment by RaphaelS1** [comment]
on hold until https://github.com/mlr-org/mlr3proba/pull/133 closed

**Comment by RaphaelS1** [comment]
All renamed to snake case, old constructors soft deprecated and will be deleted in v0.4.0 (next release will be v0.2.0).
