### ISSUE TITLE
Kernels vs distributions

### ISSUE THREAD

**Issue by fkiraly** [mlr-org/mlr3proba#129]
Arising from discussion with @aintoha , one question:
why are we making the distinction between kernels and distributions?
After all, kernels are non-negative functions, integrate to one, thus are also pdf of a distribution.

Is it since kernels need to satisfy the additional condition that it has no parameters? Or only a bandwith parameter? E.g., uniform distribution having upper/lower, but uniorm kernel always being symmetric?

PS: why is there no "question" label in this issue tracker?

**Comment by RaphaelS1** [comment]
Wrong repo, can you re-open in distr6?

**Comment by fkiraly** [comment]
oops, indeed
