### ISSUE TITLE
survivalsvm return type

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#13]
The `survivalsvm` package is quite frustrating in its limited documentation and even the Van Belle papers (2011a-2011b) do not make it explicitly clear what the models are predicting. Or more precisely, they give a mathematical formulation for predicting the prognostic index which should be able to be plugged straight into a c-index measure, however these are completely uninterpretable - some are negative, some are of orders of magnitude 1-05, some are orders 1e03. I am unsure how to proceed with these... but perhaps someone can understand the papers/documentation better than I and can make a more informed judgement; currently I am just returning the predictions from all model types as the `risk`

**Comment by fkiraly** [comment]
strange - is this just the continuous ranking then? I.e., is `survivalsvm` not implementing the reduction step, just the continuous ranking step?

**Comment by fkiraly** [comment]
If so, it would be a ranking model, not a survival model, and there isn't an mlr3 package where the ranking models would currently sit.

**Comment by RaphaelS1** [comment]
> If so, it would be a ranking model, not a survival model,

Well as per #12 we can still return the results under the `rank` (or `crank` etc.) predict type and assess results using discrimination measures

**Comment by fkiraly** [comment]
Hm, ok - but in that case the `survivalsvm` model would *only* have a `crank` return type, not a survival or `distr` return type.

**Comment by RaphaelS1** [comment]
Exactly. But until we know if a composition is possible then we don't have many other options

**Comment by fkiraly** [comment]
... I'm not sure adding a complete new category of algorithms (supervised continuous rankers), and within it only a single example ("survival" SVM), is a good use of your time at this moment?

**Comment by RaphaelS1** [comment]
But we aren't adding a new category as we already have the `crank` or `relrisk` or whatever we call it return type, which is consistent with every implemented survival learner. So instead of thinking about it as a model that is different because it only returns a ranking, think of it as a model that is different because it doesn't return a survival distribution - Therefore it is useful to users who are interested in comparing discrimination (which is still the most common survival task) but not to users who want a predictive distribution

**Comment by RaphaelS1** [comment]
> As a practical consideration, it may be worth thinking about how/where it sits in the mlr ecosystem. Another return type that you can call on learning tasks? Or is it a completely separate task, or task type?

Agenda point for Tuesday

**Comment by RaphaelS1** [comment]
See #31 and other discussions about composition
