### ISSUE TITLE
Move pipelines to mlr3pipelines

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#132]
* [ ] PipeOpDistrCompositor
* [ ] PipeOpCrankCompositor

**Comment by RaphaelS1** [comment]
on holds until https://github.com/mlr-org/mlr3proba/pull/133 closed

**Comment by pfistfl** [comment]
Hey @RaphaelS1 :
I am not sure, your pipelines should be moved to `mlr3pipelines`.
I guess this is more of a philosophical question, but I guess we should define a policy here?
I feel, that it makes more sense to have "things that belong together be together" from an application/user point of view.

Also, I'm a little afraid that `mlr3pipelines` will become too bloated (it already has quite a few `PipeOps`) if we add all
pipeops from all packages.

**Comment by RaphaelS1** [comment]
I think this is something to discuss during the sprint, I've added it as a discussion point. Because we should probably have a single rule for learners, measures, and pipelines to be consistent.

**Comment by RaphaelS1** [comment]
See #141 instead.
