### ISSUE TITLE
rd aliases for distrcompose pipeops

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3proba#147]
Currently the distrcompose pipeop links are broken in the mlr3book. 

The book currently assumes the following naming scheme:
`mlr_pipeops_<dict_key>`

![image](https://user-images.githubusercontent.com/7313671/92003563-7a602580-ed41-11ea-988f-68c6acd9532d.png)

If the Rd aliases would follow that convention, I guess links would fix themselves.

**Comment by RaphaelS1** [comment]
Sorry I thought I was using a template that does this automatically. Will update ASAP.

**Comment by pfistfl** [comment]
The others seem to work :)

**Comment by RaphaelS1** [comment]
'alias' changed to 'name', should fix it
