### ISSUE TITLE
glmnet or cvglmnet

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#15]
Following `mlr3survival` (https://github.com/mlr-org/mlr3survival/blob/master/R/LearnerSurvGlmnet.R) I implemented `cv.glmnet` for the survival glmnet.

But I have just found this issue https://github.com/mlr-org/mlr/issues/106 that suggests I should be using `glmnet` instead. 

Both appear to be implemented in `mlr` so I am happy to implement both options but interested to know if @mllg or @berndbischl have any further insight after 5 years?

**Comment by fkiraly** [comment]
Can't these just be two different learners, mirroring the fact that these are different modelling strategies?

If one of the two is terrible, a fair evaluation workflow would pick that up anyway.

**Comment by RaphaelS1** [comment]
This is my plan but I just want to see from the mlr team if they have any feedback on usage in this way

**Comment by mllg** [comment]
It's difficult.

Normally you would want to let the optimizer of choice deal with all hyperparameters, including the penalty `lambda`. AFAICT this is the only way to tune the model for your custom measure (e.g., a cost-sensitive measure).

However, `glmnet` evaluates many values for `lambda` during the training step, and `cv.glmnet()` uses them to tune `lambda` more efficiently than we could with a model agnostic optimizer.

So it clearly depends on the task. Having two learners seems to be the best choice for now.

**Comment by RaphaelS1** [comment]
I've now implemented both but a couple of questions arose that I can't work out if they are mistakes on my end or not:

1. When passing the `s` parameter to `glmnet`, this only works if rounded at 6d.p. This means that in `cv.glmnet` the special value `lambda.lse` always returns a risk of zero unless this is first rounded to 6d.p. This isn't a problem except that it does seem strange as the return type of `model$lambda.lse` is more than 6d.p.
2. I have had to force a default of the `s` value for `surv.glmnet` otherwise it returns risks for every possible lambda. I have selected as default the first lambda value in the sequence, i.e. `model$lambda[1]`. But I have found that this means predictions form `surv.glmnet` and `surv.cvglmnet` are identical, of course this is possible but I just want to check this does make sense

**Comment by fkiraly** [comment]
Number 2 doesn't sound right...
Here's another silly question: how does `surv.cvglmnet` cross-validate the `lambda`, if it doesn't seem to come with an output or interface point to evaluate the models in the first place?

**Comment by RaphaelS1** [comment]
From the `glmnet` documentation:

> The function runs glmnet nfolds+1 times; the first to get the lambda sequence, and then the remainder to compute the fit with each of the folds omitted. The error is accumulated, and the average error and standard deviation over the folds is computed. Note that cv.glmnet does NOT search for values for alpha. A specific value should be supplied, else alpha=1 is assumed by default. If users would like to cross-validate alpha as well, they should call cv.glmnet with a pre-computed vector foldid, and then use this same fold vector in separate calls to cv.glmnet with different values of alpha. Note also that the results of cv.glmnet are random, since the folds are selected at random. Users can reduce this randomness by running cv.glmnet many times, and averaging the error curves.

**Comment by fkiraly** [comment]
This is from here,
https://www.rdocumentation.org/packages/glmnet/versions/2.0-18/topics/cv.glmnet
right?

If so, it indeed looks like it has a special heuristic to tune `lambda`, and it looks like it also returns a fit with that `lambda`, obtained on the training set, thus a separate learner is justified. It keeps `alpha` untuned, however.

**Comment by RaphaelS1** [comment]
I think we have justified both and I've added in notes similarly to as noted here:
https://github.com/mlr-org/mlr/issues/1030
