### ISSUE TITLE
Design of measures - Many vs args

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#152]
Is it 'better'/preferred to have multiple separated measures or fewer measures with parameters?

e.g. In proba we have six concordance measures all in `surv.cindex` which are further specified with a `weight_meth` argument:

```R
# harrell's
msr("surv.cindex")
# uno's
msr("surv.cindex", weight_meth = "G2")
```

Same also for standard errors:
```R
msr("surv.graf")
msr("surv.graf", se = TRUE)
```

The advantage is much less measures but the disadvantage is then `msrs` can't be used and also conflicting IDs

**Comment by adibender** [comment]
I'd vote for more measures than

**Comment by RaphaelS1** [comment]
But then we get back to the problem of having 20+ measures when many of them are pretty much identical.
e.g. `surv.graf` and `surv.schmid` are currently separated, but actually they are the same measure but in one line of one equation there's a variable squared. Also then we have a blow-up when we include standard errors.

@mllg do you think there's any possibility that `msrs` could include a mechanism for passing parameters to individual measures or is this too complex?

**Comment by fkiraly** [comment]
@RaphaelS1, @adibender, in my opinion, this is a specials case of the "what to encapsulate as a single object" discussion. The two extremes are one single mega-learner or measure class, which allows to choose any measure by parameters, or individual learners/measures, none of which has any parameters. Both of which are obviously idiotic choices.

The "sweet spot", in general, is in my opinion:
* shorthands with sensible defaults for the most frequently used or most important measures
* make parameters the choices that define a mathematically, conceptually, or semantically sensible parametric family. This usually includes things like degrees, weights, regularization parameter values, hoice of algorithmic methos of computing the same estimator. It may also include different estimates for the same estimate.

In the above example: I would indeed collate the concordance indices in one metric, and expose things like different weightings via parameter. Unless the mathematical formula is substantially different from the standard C-index.

**Comment by RaphaelS1** [comment]
Whilst I agree with you in principle Franz, and in the case of cindex the measures are identical except for a single line, hence my decision to collect them in one however this makes it harder to utilise with the current mlr3 interface as the `msrs` function does not allow multiple args to be passed to it. I think I'll just open an issue in `mlr3`

**Comment by RaphaelS1** [comment]
Closing for now. Current interface uses args and whilst this is not efficient in terms of SEs, this feature is rarely used in practice and most comparison of this kind is deferred to mlr3benchmark
