### ISSUE TITLE
How to handle distr learners with unequal time-points

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#153]
This is very much an edge case as most learners will predict a distribution for the same time points, however cforest and ctree are a counter-example to this, reprex:

``` r
library(mlr3extralearners)
library(mlr3proba)
library(mlr3)
#> 
#> Attaching package: 'mlr3'
#> The following objects are masked from 'package:mlr3extralearners':
#> 
#>     lrn, lrns
l = lrn("surv.cforest")
t = tsk("rats")
p = l$train(t)$predict(t)
p$score(msr("surv.graf"))
#> Warning in matrix(unlist(cdf), nrow = length(data[[1]]), ncol = length(data)):
#> data length [11925] is not a sub-multiple or multiple of the number of rows [37]
#> Warning in matrix(unlist(data), ncol = ncol(cdf)): data length [11925] is not a
#> sub-multiple or multiple of the number of rows [40]
#>  surv.graf 
#> 0.06839911
```

<sup>Created on 2020-09-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<sup>Created on 2020-09-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This means that no scoring rules can be 'trusted' for these learners as there results are likely meaningless. Strictly speaking we could re-write the scoring rules so that each observation is evaluated separately and then combined, this would give a precise result for these edge cases but will also be vastly less efficient.

**Comment by RaphaelS1** [comment]
This is a distr6 issue.

**Comment by fkiraly** [comment]
@RaphaelS1, not necessarily a pure distr6 issue?

It is also an issue of the implementation of the scores.

A "proper" implementation of the integrated Brier score, CRPS, Graf score and variants, should *not* be impeded by the exact form of the predictive distr, e.g., whether discrete distributions are supported at all the same time points.

The problem seems rather to be an implementation of the losses which is not robust against that, than a distr6 issue, to me.

**Comment by RaphaelS1** [comment]
> A "proper" implementation of the integrated Brier score, CRPS, Graf score and variants, should not be impeded by the exact form of the predictive distr, e.g., whether discrete distributions are supported at all the same time points.

That's not the problem here. I had initially thought it was but found I was wrong. The problem was actually occurring when vector distributions are formed of `WeightedDiscrete` distributions of different lengths, which should never really happen. The fix was simple, as all these distributions are formed of matrices, just truncate the matrices so that all have the same number of rows, which is equivalent to truncating a distribution at a given value
