### ISSUE TITLE
Add pipeop PredictionSurv -> PredictionClassif

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#159]
Three methods:

1. Surv -> Multilabel: Create a vector of `k` points or a given width and threshold `distr` at a given value (say 0.5) to give binary predictions over `k` labels
2. Surv -> Multilabel: Same as above but use `response` and then I(response <= k) gives binary prediction (or reverse inequality given positive class)
3. Surv -> Binary: Threshold crank given some value I(crank <= alpha) for prediction

Hyper-parameters:
*  (1) and (3) require alpha for thresholding
*  (1) and (2) require `k` or `width` for multi-label

**Comment by fkiraly** [comment]
Which way round is this? 
Is the input surv and output multilabel, or is the input multilabel and output surv?

The latter would be the scitype of the typical kind of "binning classification strategy", no?

**Comment by RaphaelS1** [comment]
Note this is a prediction not task reduction. So this is not a task reduction and using binned classification to solve the survival task but instead using survival learners as usual but then converting predictions to classification (binary or multilabel)

**Comment by fkiraly** [comment]
What is the use case for that, as a pipeop?
Can´t you just easily get these probabilities from the return distr´s cdf if you want to inspect them?

I´d also find the reduction that you mention interesting.

**Comment by RaphaelS1** [comment]
> What is the use case for that, as a pipeop?
Can´t you just easily get these probabilities from the return distr´s cdf if you want to inspect them?

Well consider that there are multiple ways to do this transformation and therefore a pipeop can control this with hyper-parameters, including setting cut-offs and selecting the method. But yes essentially for the `distr` transformation the code is just `p$distr$cdf(times) <= alpha` where `alpha` is the cutoff, `p` is the prediction, `times` is given or all time-points.

> I´d also find the reduction that you mention interesting.

https://github.com/mlr-org/mlr3proba/issues/11
Will probably implemented in the new year

**Comment by fkiraly** [comment]
So I´m slightly confused - if this is a pipeop, doesn´t this automatically do reduction? 
I.e., it changes the scitype from being a distr output survival learner to being a probabilistic classifier?

May I also ask for clarification regarding the use case?
E.g., you want to do X, and you have Y, and you solve it by doing Z.

**Comment by RaphaelS1** [comment]
> So I´m slightly confused - if this is a pipeop, doesn´t this automatically do reduction?

No it does composition in the same way as

* https://github.com/mlr-org/mlr3proba/blob/master/R/PipeOpCrankCompositor.R
* https://github.com/mlr-org/mlr3proba/blob/master/R/PipeOpDistrCompositor.R

> I.e., it changes the scitype from being a distr output survival learner to being a probabilistic classifier?

It changes a `PredictionSurv` to `PredictionClassif`

> May I also ask for clarification regarding the use case?
E.g., you want to do X, and you have Y, and you solve it by doing Z.

Consider a standard survival workflow, you find a model, tune it, make predictions, etc. Then let `p` be the `PredictionSurv` object and `alpha` some probability, you want to consider any of (ignore the `po` names for now):

1. Which individuals are alive at time, t. Either you could use `p$distr$surv(t) < alpha` for `po("binarysurv", t = 5, alpha = 0.5)`. The first is relatively simple but returns a simple vector whereas the latter returns a `PredictionClassif` object
2. Probabilities discretised over time (transformation to multi-label classification). Mathematically there is no *need* to do this but it is common simply for interpretation.

This proposed pipeop/pipeline is not covering a mathematical requirement but will serve users who are less comfortable in the survival domain or people who can better explain classification settings; which is common in survival (as we've discussed for years).

**Comment by fkiraly** [comment]
>>So I´m slightly confused - if this is a pipeop, doesn´t this automatically do reduction?

>No it does composition in the same way as

Ah, so you still train it as a survival learner (with the more informative outcome), but just report the classification outcome?

Regarding the use case: in 1, why is the `PredictionClassif` preferable above the vector or probabilities? 
Note that you also have no longer access to the `PredictionSurv` object if you build the entire pipeline, right? Would you then not have to build two pipelines, one with and one without the pipeop, to get access to both?
Further, don´t people in this use case usually want to vary `alpha`, so fixing `alpha` in the pipeop would prevent one from getting the desired values for multiple values of `alpha`?

In use case 2, that does sound like reduction, no? As in #11?

In either case, still slightly unclear what the user journey would look like. E.g., as discussed above:
* would the user build multiple models with the pipeop, and one without, or just one overall?
* what would a sketch of the full modelling and diagnostics workflow look like?

**Comment by RaphaelS1** [comment]
No, to be clear this is a pipeop not a pipeline. So we can just think of it as a function applied to a prediction object. So in the workflow this is just some post-hoc procedure
