### ISSUE TITLE
dens.squared

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#162]
Opening this issue for discussion about #161 
@aintoha please clone and use this branch: https://github.com/mlr-org/mlr3proba/tree/MeasureDensSquaredloss

CC @fkiraly

**Comment by aintoha** [comment]
Yes, I haven't changed that yet. I use example that only include bandwidth for now. But, I still get the error. Even I remove the 'bw' (I set bw = 1 and remove all the lines (47 - 56)).

**Comment by RaphaelS1** [comment]
Works fine for me:

``` r
library(mlr3)
library(mlr3proba)
learner = lrn("dens.kde", bandwidth = 0.5)
task = tsk("precip")
p = learner$train(task)$predict(task)
m = msr("dens.squared")
p$score(m, task = task, learner = learner)
#> dens.squared 
#>  -0.09442422
```

<sup>Created on 2020-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aintoha** [comment]
it works for me now too. 

I am thinking that to call the bandwidth and kernel easier, we should out the bandwidth and the kernel. Currently, I did the code below for "LearnerDensKDE". 

`list(distr = Distribution$new(
          name = paste(self$param_set$values$kernel, "KDE"),
          short_name = paste0(self$param_set$values$kernel, "_KDE"),
          pdf = pdf,
          type = set6::Reals$new()), bw = bw, kernel = kernel)`

And I think this will get rid of `if else` in the `MeasureDensSquaredLoss`.

**Comment by RaphaelS1** [comment]
Very good idea. It would also make sense to unify all kernel names in the output (not sure if this is what you did already). Eg. So instead of "e, epan, epanechnikov" they all return "epan" (or whatever you choose)

**Comment by aintoha** [comment]
Yes, so I will try to see how that goes for `LearnerDensKDE` and see how `MeasureDensSquaredLoss` can call the learners.

**Comment by fkiraly** [comment]
@fkiraly, @aintoha, did we discuss or resolve the dispatch in the measure?
I don´t think there should be dispath in the measure, just method calls.

**Comment by RaphaelS1** [comment]
@aintoha instead of using 

```R
list(
   distr = Distribution$new(name = paste(self$param_set$values$kernel, "KDE"),
                 short_name = paste0(self$param_set$values$kernel, "_KDE"), pdf = pdf, type = set6::Reals$new()),
   bw = bw,
   kernel = kernel
)
```

please use 

```R
structure(list(distr = Distribution$new( name = paste(self$param_set$values$kernel, "KDE"), short_name = 
                paste0(self$param_set$values$kernel, "_KDE"), pdf = pdf, type = set6::Reals$new()),
                     bw = bw,
                     kernel = kernel),
         class = "dens.kde")
```

and change the class to whatever the learner is called.
