### ISSUE TITLE
Installation fails if mlr3pipelines is not installed because of mlr_graphs import

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3proba#166]

**Comment by RaphaelS1** [comment]
I don't see how this could be possible if it works on CRAN but I'll take your word for it! I'll look into ths

**Comment by RaphaelS1** [comment]
Removed pipelines and proba, restarted R, installed proba with no problems.

**Comment by larskotthoff** [comment]
The error I got was

    installing to /tmp/Rtmppt273e/Rinst2657ee4fd58632/00LOCK-mlr3proba/00new/mlr3proba/libs
    ** R
    ** data
    *** moving datasets to lazyload DB
    ** inst
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    *** copying figures
    ** building package indices
    ** testing if installed package can be loaded from temporary location
    Error: package or namespace load failed for ‘mlr3proba’:
     .onLoad failed in loadNamespace() for 'mlr3proba', details:
      call: get(x, envir = ns, inherits = FALSE)
      error: object 'mlr_graphs' not found
    Error: loading failed
    Execution halted
    ERROR: loading failed

But now that you mention it, I can't seem to be able to reproduce that either.

**Comment by RaphaelS1** [comment]
So strange... was that from GH remotes or CRAN install?

**Comment by larskotthoff** [comment]
GH remotes.

**Comment by lindeloev** [comment]
I got this error too with `remotes::install_github("mlr-org/mlr3proba")`. Installing `mlr3pipelines` from CRAN solved the problem.

**Comment by RaphaelS1** [comment]
I've removed pipelines and proba, tried install from GH, no error. 

The other weird thing is that the error I get when running `utils::getFromNamespace("mlr_graphs", ns  = "mlr3pipelines")` (which is the only relevant line in proba) gives a different error if pipelines isn't installed: `Error in loadNamespace(name) : there is no package called ‘mlr3pipelines’.`

Also this line is called only if pipelines is already loaded or if proba is loaded and then pipelines is loaded, so it shouldn't be triggered on install.

I guess for now let's just leave this issue open, but it would be good to get the session info when the error occurs, probably two late for you two as pipelines if you've already installed pipelines.

**Comment by RaphaelS1** [comment]
Closing for now, will investigate further if it comes up again
