### ISSUE TITLE
Update, extend, cleanup distrcompositor

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#175]
Following changes are required:

1. Remove composition from `crank` to `distr` - This doesn't make any sense for abstract rankings, composition can only make sense for `lp`to `distr`.
2. Add composition from `response` to `distr` - This can be most efficiently done by abstracting the probabilistic regression composition and using the same functions in both

(1) is higher priority as its results are meaningless.

**Comment by fkiraly** [comment]
>Remove composition from crank to distr

Why? I can imagine cases where this makes sense!

The most obvious case would be calibration methods, e.g.: stick your predicted rank into a distribution as shape or location parameter; then do grid-tuning (or gradient descent tuning if/once autodiff is supportec).

This is very common for probabilistic classifiers, and the probabilistic regression/survival counterpart is also not absurd.

**Comment by RaphaelS1** [comment]
Sorry I should clarify this:

The current composition assumes `crank = lp` and then uses a semi-parametric composition, e.g. h(t) =  h_0(t)lp for baseline h_0.

However the new composition type to end (point 2.) instead uses the composition you describe, which can handle `crank`

**Comment by fkiraly** [comment]
ah, makes sense.
