### ISSUE TITLE
networks and probabilistic supervised regression

### ISSUE THREAD

**Issue by fkgruber** [mlr-org/mlr3proba#181]
Regarding the probabilistic supervised regression plans,  do you plan to implement network inference?
Say I have the following data generating function where both Treatment and Outcome are essentially supervised regression tasks but Treatment is also an input to the Outcome.
![image](https://user-images.githubusercontent.com/4311763/105512599-4f01b700-5c9f-11eb-8b95-3fd28ccb78b1.png)

Once fitted I would like to be able to generate samples from the model and even setting variables to specific values and see the effect downstream. Similar to, say, bnlearn R package.

**Comment by RaphaelS1** [comment]
Good question, the prob regr interface is only planned so far. At the moment we only handle transforming (standard) regression to distributions by making transformations. The plan is to expand our interface to include learners like (e.g.) LearnerRegrBUGS which would just connect to BUGS and allow users to specify their own models.

If you have specific ideas for design/implementation please feel free to share them.

**Comment by fkgruber** [comment]
a Stan learner would be nice.

if you supported this sort of network there could be another package interfacing bnlearn so that we can learn the connections and then use mlr3prob to sample and make prediction on the resulting networks.

**Comment by fkiraly** [comment]
@fkgruber, contributions would also be very much welcome :-)
Currently, we have no major work items on the roadmap for probabilistic regression, but it would be really great to have.

**Comment by fkgruber** [comment]
An interface to tfprobability would be nice too.

Is there any documentation for contributors?

**Comment by RaphaelS1** [comment]
I guess tfprobability would be a separate interface but we could consider a similar structure to mlr3keras.

As for contributing, we have lots of documentation in the mlr3book but this wouldn't be covered as we are discussing an entirely new interface.
