### ISSUE TITLE
Export functions for mcboost survival extension

### ISSUE THREAD

**Issue by carobec** [mlr-org/mlr3proba#204]
Hi,
At the moment, I am working on the survival extension of mcboost (https://github.com/mlr-org/mcboost). 
For calculating the residuals for the boosting algorithm, I need similar functions to the ones used in the Integrated Graf Score. 
Would it be anyhow possible to export the following functions? 

`assert_surv`
`c_get_unique_times`
`c_weight_survival_score`

Thank you :)

**Comment by RaphaelS1** [comment]
Sure, I'll export the second two as hidden functions though so
`c_get_unique_times` -> `.c_get_unique_times`
`c_weight_survival_score` -> `.c_weight_survival_score`

**Comment by carobec** [comment]
Thank you!

**Comment by fkiraly** [comment]
@carobec, *actually* - would you, in addition, be interested in working on the sub-module for probabilistic loss functions?

**Comment by carobec** [comment]
@fkiraly At the moment, my entire concentration is on my master's thesis (extension of mcboost to survival). However, depending on how my future path looks like, I would be interested then.

**Comment by carobec** [comment]
@RaphaelS1 Thank you very much! That helps a lot :)
