### ISSUE TITLE
Predictions with predict type `distr` are very large

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3proba#206]
This very small prediction object already takes > 5Mb with distr, and ~70 kB without:
```r
 library(mlr3)
 task = tsk("rats")
 learner = lrn("surv.coxph", predict_type = "crank")
 p = learner$train(task, row_ids = 1:20)$predict(task, row_ids = 21:30)
 pryr::object_size(p)

 # drop distr preds
 tab = as.data.table(p)
 p = as_prediction_surv(tab[, -"distr"])
 pryr::object_size(p)
```

**Comment by pfistfl** [comment]
Addition: This scales especially poor for larger objects (> 1000 Obs) where I get object sizes of > 400 MB.
I think for train-test with coxph on ~1000 Observations, a large part of the compute goes into creating the distr outcomes.

**Comment by pfistfl** [comment]
Could we add a `predict_type` survival_matrix that stores/returns the NObs. x TimePoints matrix instead. 
The distr objects could be constructed from it later on and it might scale slightly better?  (i.e. only linearly in N and T)

**Comment by mllg** [comment]
Wait, it is possible to represent the distributions as a matrix? Are the timepoints identical for all iterations? Note that we store the probabilities in PredictionRegr also as a matrix for efficient storage, so it should be very simple to port this to proba.

**Comment by pfistfl** [comment]
I might have gotten that wrong, but I think this is what e.g. `scikit-survival` uses? 
https://scikit-survival.readthedocs.io/en/stable/api/generated/sksurv.tree.SurvivalTree.html#sksurv.tree.SurvivalTree.predict_survival_function

**Comment by RaphaelS1** [comment]
@pfistfl 

> I think for train-test with coxph on ~1000 Observations, a large part of the compute goes into creating the distr outcomes.

This is a known bottleneck

> Could we add a predict_type survival_matrix that stores/returns the NObs. x TimePoints matrix instead.
The distr objects could be constructed from it later on and it might scale slightly better? (i.e. only linearly in N and T)

This is exactly my plan but it isn't currently possible because of the above bottleneck. Once that's fixed then what you suggest is the clear solution. Though it isn't *always* the sam time-points for all predictions but it's easy to force it to be (carry forward last time)

@mllg

> Wait, it is possible to represent the distributions as a matrix? Are the timepoints identical for all iterations? Note that we store the probabilities in PredictionRegr also as a matrix for efficient storage, so it should be very simple to port this to proba.

As above. Once the contruction bottleneck is fixed (see extensive, ongoing discussions) then this is an easy fix by storing as matrices and only converting when called

**Comment by RaphaelS1** [comment]
```
r$>  library(mlr3) 
     task = tsk("rats") 
     learner = lrn("surv.coxph", predict_type = "crank") 
     p = learner$train(task, row_ids = 1:20)$predict(task, row_ids = 21:30) 
     pryr::object_size(p) 
     
     # drop distr preds 
     tab = as.data.table(p) 
     p = as_prediction_surv(tab[, -"distr"]) 
     pryr::object_size(p)                                                                                     

103 kB
101 kB
```
