### ISSUE TITLE
Add cforest

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#21]
https://github.com/mlr-org/mlr/blob/master/R/RLearner_surv_cforest.R

**Comment by adibender** [comment]
I will wait until this is merged: https://github.com/mlr3learners/mlr3learners.partykit/pull/4

**Comment by RaphaelS1** [comment]
Yeah makes sense, thanks

**Comment by RaphaelS1** [comment]
@adibender that PR has been merged, I think we should include ctree as well as cforest, especially as even the authors say "Ensembles of conditional inference trees have not yet been extensively tested, so this routine is meant for the expert user only and its current state is rather experimental." Probably makes sense to get in contact with the maintainer of [the repo](https://github.com/mlr3learners/mlr3learners.partykit) first and then directly add these learners to there. There's a few additions required for proba learners (including adding imports, changing zzz.R, and updating autotest helpers), so if you prefer could add it to mlr3proba and then I can port it to the org

**Comment by adibender** [comment]
Ok, thanks. I'll have a look asap

**Comment by adibender** [comment]
I just looked into ctree. It either returns the median survival time (which is `Inf`) for censored observations or a `survfit` object for each observation. I guess that type of output is fine and just has to be translated into distr6 Distribution

**Comment by RaphaelS1** [comment]
Yeah that's fine, look at https://github.com/mlr-org/mlr3proba/blob/master/R/LearnerSurvKaplan.R for a `distr` example for `survfit`

**Comment by RaphaelS1** [comment]
And as a side point, median survival time is not the same as predicted time-to-event so probably shouldn't go in the `response` variable but can be used for `crank`. A user can then use a pipeop to produce a `response` time-to-event if they want one
