### ISSUE TITLE
Add arguments t_max / p_max for measure surv.graf

### ISSUE THREAD

**Issue by tess-st** [mlr-org/mlr3proba#220]
There should be an argument to set 
- [x] an interval `[t_min; t_max]` for which the brier / graf score is integrated over, and
- [x] `p_max` which will evaluate up to the given proportion of censoring

quick fix for 1: right now the only solution is to set `times = seq(t_min, t_max)`

**Comment by RaphaelS1** [comment]
Thanks!

**Comment by RaphaelS1** [comment]
Will do this at the same time as #198 (which will be sometime in next 3 weeks)
