### ISSUE TITLE
Add density learners

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#23]
https://vita.had.co.nz/papers/density-estimation.pdf
https://cran.r-project.org/web/packages/kdensity/
https://bookdown.org/egarpor/PM-UC3M/npreg-npdens.html
https://rdrr.io/cran/demoKde/man/kde.html

**Comment by fkiraly** [comment]
I think before we do that, we should work out the API for density estimators - the return object is a single density, not one per test point as in the case of supervised probabilistic prediction. 
@aintoha has had some thoughts about this - let's have an off-line discussion.

**Comment by RaphaelS1** [comment]
Agreed, as per #24 I'm going to get the survival task finished for a 0.1 release before thinking about the density task

**Comment by RaphaelS1** [comment]
| Learner | Class | Package |
|---------|-------|--------|
| dens.hist | Histogram | graphics |

**Comment by aintoha** [comment]
| Learner  | Class     | Package  | Implemented |
|----------|-----------|----------|-------------|
| hist     | Histogram | graphics | Y           |
| histash1 | Histogram | ash      |             |
| kdeks    | KDE       | ks       | Y           |
| kdenp    | KDE       | np       |             |
| kdesm    | KDE       | sm       | Y           |
| kdepd    | KDE       | plugin   |             |

**Comment by aintoha** [comment]
| Learner           | Class             | Package    | Implemented | Priority  |
|-------------------|-------------------|------------|-------------|-----------|
| hist              | Histogram         | graphics   | Y           | 1         |
| histash1          | Histogram         | ash        |             | 1         |
| kdeks             | KDE               | ks         | Y           | 1         |
| kdenp             | KDE               | np         |             | 1         |
| kdesm             | KDE               | sm         | Y           | 1         |
| kdepd             | KDE               | plugin     |             | 1         |
| kdebkde           | KDE               | KernSmooth |             | 3         |
| kdegern           | KDE               | GenKern    |             | 3         |
| kdekerd           | KDE               | kerdiest   |             | 3         |
| kdekdens          | KDE               | kdensity   |             | 3         |
| kdedens           | KDE               | stat       |             | 1         |
| densloglikelihood | DensLogLikelihood | locfit     |             | 2         |
| denspen           | DenPenalized      | pendensity |             | 2         |
| densgss           | DensPenalized     | gss        |             | 2         |
| densls            | DensPenalized     | logspline  |             | 2         |
| denspm            | DensTautString    | ftnonpar   |             | 3         |

**Comment by RaphaelS1** [comment]
Thanks very much! Very useful, to confirm 1 is high priority and 3 is low priority?

**Comment by aintoha** [comment]
Yes, 1 is high priority and 3 is less.
