### ISSUE TITLE
Predict types with mlr3 learners

### ISSUE THREAD

**Issue by Selenia94** [mlr-org/mlr3proba#231]
Hello :) 

I am currently working on several survival machine learning models using mlr3proba. I’ve been wondering about the predict types, especially “distr” and “crank”. I’ve been reading the wiki “implementing predict types” to understand how these two are related and where they come from when a learner returns a survival distribution.

I have not been able to reproduce the predicted survival distribution (and the associated risk ranks) given by a mlr3learner (for example a survival random forest from the package randomForestSRC) when using the package directly (I am trying to do it “by hand”). For instance with a randomForestSRC learner: 

```{r}
set.seed(123)
# Using rats dataset for the example
task <- tsk("rats")
train_set <- sample(task$nrow, 0.8 * task$nrow)
test_set <- setdiff(seq_len(task$nrow), train_set)

# Learner with mlr3proba
learner <- lrn("surv.rfsrc", seed = -123)
learner$train(task, row_ids = train_set)

# Prediction 
prediction <- learner$predict(task, row_ids = test_set)

# Times of interest (first individual)
times <- prediction$distr[1]$getParameterValue("x")
times
[1]   0.000  34.000  39.000  40.000  45.000  49.000  50.000  54.000  55.000  66.000  
[11]  67.000  68.000  70.000  71.000  73.000  75.000  77.000  78.000  79.000   80.000  
[21]  81.000  84.000  86.000  88.000  89.000  92.000  94.000  96.000 101.000 102.000 
[30] 103.000 104.000 104.001

# Predicted survival (first individual)
head(prediction$distr[1]$survival(times))
[1] 1.0000000 1.0000000 0.9959047 0.9863968 0.9863968 0.9644890


# Comparison with a learner from randomforestSRC directly
rf <- rfsrc(Surv(time, status) ~ ., data = rats[train_set,], seed = -123)

# Prediction
prediction_rf <- predict(rf, newdata=rats[test_set,])

# Times of interest
times_rf <- c(0, prediction_rf$time.interest)
times_rf
[1]   0  34  39  40  45  49  50  54  55  66  67  68  70  71  73  75  77  78  79  80  81  84  86  
[24] 88  89  92  94  96 101 102 103 104

# Predicted survival (first individual)
surv <- as.matrix(prediction_rf$survival)
surv <- cbind(1, surv)
head(surv[1,])
[1] 1.0000000 1.0000000 0.9958962 0.9863034 0.9863034 0.9642449
```

I do not understand why the times of interest do not match between the 2 methods (one more value with mlr3 learner of 104.001) and why the survival distributions are not equal (the example above is for the first individual). 

I also tried to manually compute the associated risk ranks and the C-index, which give me opposite results from the ones obtained with mlr3 learner:

```{r}
# Risk ranks obtained with mlr3 learner
head(prediction$crank)
[1] -100.07150 -100.07150 -103.92557 -100.05426  -95.00054  -98.64565

# Corresponding c-index
cindex <- msr("surv.cindex", weight_meth="I")   
prediction$score(cindex)

surv.harrell_c 
     0.7484277  

# Comparison with the risk ranks calculated "by hand" from the rf object
risk <- -apply(1-surv, 1, function(.x) sum(c(.x[1], diff(.x)) * times_rf))
head(risk)
[1] -12.6619368 -12.6619368  -0.3107318 -12.7258025 -38.9598687 -17.9766316

# Corresponding c-index
1-concordance(Surv(rats[test_set,]$time, rats[test_set,]$status) ~ risk)$concordance
[1] 0.284375
```

Can you tell me where I am wrong, what I do not understand and/or what I am obviously missing?

I am sorry if it is a dumb question! 

Thank you so much in advance!

Have a good day :) 
Agathe

**Comment by RaphaelS1** [comment]
Hey, these are all great questions! We clearly need to re-write some stuff in the book!

> I have not been able to reproduce the predicted survival distribution (and the associated risk ranks) given by a mlr3learner (for example a survival random forest from the package randomForestSRC) when using the package directly (I am trying to do it “by hand”). For instance with a randomForestSRC learner:

1. The predicted risk is different because we currently calculate risk in a different way. The reason for this is because we previously wanted to unify how risk was calculated across learners. However after a paper which we have *just* written (preprint available this week) we have decided to update how risk is calculated from distributions. Originally it was the negative mean survival time, we will be updating this to the sum of the predicted cumulative hazard - which happens to be the same method as rfsrc
2. The reason why the predicted survival is different however appears to be a bug. I've done some testing and it seems the problem is in fitting and not prediction - @sebffischer do you have time to investigate? It's likely that a hyper-parameter is/isn't being passed through properly. I've added a reprex to the bottom of this issue ('Reprex 2'). If you don't have time to investigate then I can find time in a couple weeks.

> I do not understand why the times of interest do not match between the 2 methods (one more value with mlr3 learner of 104.001) and why the survival distributions are not equal (the example above is for the first individual).

As said above, we wanted to unify ranks as the negative mean survival time. However this required extrapolating the predicted survival distribution in order to ensure the final predicted probability is zero. We have since decided this is not an appropriate method and will be reverting this.

> I also tried to manually compute the associated risk ranks and the C-index, which give me opposite results from the ones obtained with mlr3 learner:

I love this question because it actually answers your question about about the '104.001'. When you 'manually' created the risk, you were applying the formula to calculate the expectation from a distribution. However, this formula fails when the distribution prediction is 'improper', i.e. when the final predicted probability is >0. By 'fixing' this (note we didn't have to use '104.001', we could have equally used '1e6' or any other number), the concordance is now the same (see 'Reprex 1').

___

## Reprex 1


``` r
set.seed(123)
# Using rats dataset for the example
task <- tsk("rats")
#> Error in tsk("rats"): could not find function "tsk"
train_set <- sample(task$nrow, 0.8 * task$nrow)
#> Error in sample(task$nrow, 0.8 * task$nrow): object 'task' not found
test_set <- setdiff(seq_len(task$nrow), train_set)
#> Error in as.vector(x): object 'task' not found

# Learner with mlr3proba
learner <- lrn("surv.rfsrc", seed = -123)
#> Error in lrn("surv.rfsrc", seed = -123): could not find function "lrn"
learner$train(task, row_ids = train_set)
#> Error in eval(expr, envir, enclos): object 'learner' not found

# Prediction 
prediction <- learner$predict(task, row_ids = test_set)
#> Error in eval(expr, envir, enclos): object 'learner' not found

# Times of interest (first individual)
times <- prediction$distr[1]$getParameterValue("x")
#> Error in eval(expr, envir, enclos): object 'prediction' not found

# Comparison with a learner from randomforestSRC directly
rf <- rfsrc(Surv(time, status) ~ ., data = rats[train_set,], seed = -123)
#> Error in rfsrc(Surv(time, status) ~ ., data = rats[train_set, ], seed = -123): could not find function "rfsrc"

# Prediction
prediction_rf <- predict(rf, newdata=rats[test_set,])
#> Error in UseMethod("predict"): no applicable method for 'predict' applied to an object of class "function"

# Times of interest
times_rf <- c(0, prediction_rf$time.interest, 104.0001)
#> Error in eval(expr, envir, enclos): object 'prediction_rf' not found

# Predicted survival (first individual)
surv <- as.matrix(prediction_rf$survival)
#> Error in as.matrix(prediction_rf$survival): object 'prediction_rf' not found
surv <- cbind(1, surv, 0)
#> Error in cbind(1, surv, 0): object 'surv' not found

# Corresponding c-index
cindex <- msr("surv.cindex", weight_meth="I")   
#> Error in msr("surv.cindex", weight_meth = "I"): could not find function "msr"


# Comparison with the risk ranks calculated "by hand" from the rf object
risk <- -apply(1-surv, 1, function(.x) sum(c(.x[1], diff(.x)) * times_rf))
#> Error in apply(1 - surv, 1, function(.x) sum(c(.x[1], diff(.x)) * times_rf)): object 'surv' not found


# Corresponding c-index
round(prediction$score(cindex), 2)
#> Error in eval(expr, envir, enclos): object 'prediction' not found
1 - concordance(Surv(rats[test_set,]$time, rats[test_set,]$status) ~ risk)$concordance
#> Error in concordance(Surv(rats[test_set, ]$time, rats[test_set, ]$status) ~ : could not find function "concordance"
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

___

## Reprex 2

``` r
set.seed(123)
# Using rats dataset for the example
task <- tsk("rats")
#> Error in tsk("rats"): could not find function "tsk"
train_set <- sample(task$nrow, 0.8 * task$nrow)
#> Error in sample(task$nrow, 0.8 * task$nrow): object 'task' not found
test_set <- setdiff(seq_len(task$nrow), train_set)
#> Error in as.vector(x): object 'task' not found

# Learner with mlr3proba
learner <- lrn("surv.rfsrc", seed = -123)
#> Error in lrn("surv.rfsrc", seed = -123): could not find function "lrn"
learner$train(task, row_ids = train_set)
#> Error in eval(expr, envir, enclos): object 'learner' not found

# Comparison with a learner from randomforestSRC directly
rf <- rfsrc(Surv(time, status) ~ ., data = rats[train_set, ], seed = -123)
#> Error in rfsrc(Surv(time, status) ~ ., data = rats[train_set, ], seed = -123): could not find function "rfsrc"

all.equal(rf, learner$model())
#> Error in mode(current): object 'learner' not found
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sebffischer** [comment]
I will try to fix it!

**Comment by sebffischer** [comment]
There is nothing to fix, both the training and the prediction are implemented correctly. 
The difference is related to the `survival` method of the `distr` return type.  

``` r
library(mlr3proba)
#> Loading required package: mlr3
library(mlr3extralearners)
#> 
#> Attaching package: 'mlr3extralearners'
#> The following objects are masked from 'package:mlr3':
#> 
#>     lrn, lrns
library(randomForestSRC)
#> 
#>  randomForestSRC 2.14.0 
#>  
#>  Type rfsrc.news() to see new features, changes, and bug fixes. 
#> 
task = tsk("rats")

learner = lrn("surv.rfsrc", seed = -314)
learner$train(task)
model_rf = rfsrc(formula = task$formula(), data = task$data(), seed = -314)

# Prediction
pred <- predict(learner$model, newdata = task$data())
pred_rf <- predict(model_rf, newdata = task$data())

# Times of interest
times_rf <- c(0, pred_rf$time.interest)

# Predicted survival (first individual)
surv_rf <- as.matrix(pred_rf$survival)
surv_rf <- cbind(1, surv_rf)
surv <- as.matrix(pred$survival)
surv <- cbind(1, surv)

sum(abs(surv - surv_rf))
#> [1] 0
# --> The model is fitted correctly 

learner_rf = learner$clone(deep = TRUE)
learner_rf$state$model = model_rf

pred = learner$predict(task)
pred_rf = learner_rf$predict(task)
all.equal(pred$distr[1]$parameters(), pred_rf$distr[1]$parameters())
#> [1] TRUE
# --> The prediction is implemented correctly 

# The rounding difference results from the `survival` method 
pred_rf$distr[1]$survival(times_rf) - surv_rf[1, ]
#>  [1] 0.000000e+00 1.286501e-05 3.212709e-04 3.212709e-04 2.434433e-04
#>  [6] 3.102633e-03 3.176561e-03 3.176561e-03 3.176561e-03 3.176561e-03
#> [11] 3.176561e-03 4.302737e-03 4.302737e-03 5.314271e-03 5.314271e-03
#> [16] 5.386325e-03 5.391444e-03 5.391444e-03 5.553626e-03 5.553626e-03
#> [21] 5.553626e-03 5.566464e-03 5.566464e-03 5.566464e-03 5.485827e-03
#> [26] 7.019868e-03 7.483117e-03 6.910587e-03 6.158382e-03 7.797240e-03
#> [31] 7.797240e-03 7.019978e-03 5.238064e-03 3.597547e-03
```

<sup>Created on 2021-12-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by RaphaelS1** [comment]
I'm not sure you've checked the right thing here? Looks like you've just checked if `seed` works. Ah just looking at my `all.equal` just looks like clock time is different, which is fine. Cool so absolute error is basically identical to 3d.p. which is fine. Thanks @sebffischer !

**Comment by sebffischer** [comment]
What I wanted to show with this reprex is that there is no reason to believe that the learner is implemented incorrectly from the example by the OP. Is there anything left that you would like to be checked?

**Comment by RaphaelS1** [comment]
No I agree you're right! All good thanks :)

**Comment by Selenia94** [comment]
Many thanks for your responses ! It is all clearer now :) 
I am also interested in reading the preprint you mentioned if you can give me the link or the reference :) 
Have a good day !

**Comment by RaphaelS1** [comment]
That's great!

Preprint here: https://arxiv.org/abs/2112.04828

**Comment by Selenia94** [comment]
Thank you !
