### ISSUE TITLE
NaN surv.graf measure output for surv.gbm  

### ISSUE THREAD

**Issue by lovestat** [mlr-org/mlr3proba#236]
Hi, Thanks for developing this awesome mlr3proba package. 

I am very new using this package and have a question regarding the `surv.graf` measure - why did it output NaN when I used `surv.graf` to score `surv.gbm` ? If I use `surv.cindex`, the results are fine. For instance, using the survival example in the Chapter 8 in the mlr3 book,

```
task = tsk("rats")
learn = lrn("surv.gbm")

train_set = sample(task$nrow, 0.8 * task$nrow)
test_set = setdiff(seq_len(task$nrow), train_set)

learn$train(task, row_ids = train_set)

prediction = learn$predict(task, row_ids = test_set)

prediction$score(msr("surv.cindex"))
prediction$score(msr("surv.graf"))
```
Thanks!

**Comment by RaphaelS1** [comment]
Hi @lovestat thanks for the question. GBM returns linear predictors/risk rankings whereas Graf/Brier score evaluates distribution predictions:

``` r
library(mlr3proba)
library(mlr3extralearners)
task = tsk("rats")
learn = lrn("surv.gbm")
meas = msr("surv.graf")

learn$predict_types
#> [1] "crank" "lp"
meas$predict_type
#> [1] "distr"

learn = lrn("surv.coxph")
learn$predict_types
#> [1] "distr" "crank" "lp"

learn$train(task)$predict(task)$score()
#> surv.cindex 
#>   0.7780967
```

<sup>Created on 2021-12-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lovestat** [comment]
> Thanks! @RaphaelS1 My question is perfectly answered!
