### ISSUE TITLE
'ParameterSet' is not an exported object from 'namespace:distr6'

### ISSUE THREAD

**Issue by Ppower123** [mlr-org/mlr3proba#241]
parametric.funciton <-
  function(exprSet)
  {
    set.seed(2021)
    task <- TaskSurv$new("rats", exprSet, time = "eventtime", event = "status")
    
    lrns = lapply(paste0("surv.", c("parametric")), lrn)
    lrns[[1]]$param_set$values = list(dist = "weibull", type = "ph")
    
    resampling <- rsmp("repeated_cv", folds = 5, repeats = 1)
    
    bm <- benchmark(benchmark_grid(task, lrns, resampling))
    
    msrs <- msrs(c("surv.calib_alpha", "surv.cindex", "surv.dcalib",   "surv.uno_auc", "surv.hung_auc"))  # "surv.graf", 

    result1 <- bm$aggregate(msrs)
    
    print(result1)
    return(result1)
  }

![image](https://user-images.githubusercontent.com/91470587/148317497-70c11aec-ac3e-4564-8403-596d69b91340.png)

**Comment by RaphaelS1** [comment]
Pleaser provide a [reproducible example](https://www.tidyverse.org/help/) using the {reprex} package or I am unable to help

**Comment by RaphaelS1** [comment]
I think this is answered and have received no response so closing now.
