### ISSUE TITLE
betas not passed to simsurv

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3proba#243]
https://github.com/mlr-org/mlr3proba/blob/9011fbac849ce7ba20909aad82a9a7c86f9fc478/R/TaskGeneratorSimsurv.R#L58

Or this is a workaround for some strange non-standard evaluation in the simsurv package?

**Comment by RaphaelS1** [comment]
Looks like a typo

**Comment by RaphaelS1** [comment]
This explains why the task was never giving sensible predictions...
Closed in https://github.com/mlr-org/mlr3proba/commit/08e9d2b707ac71065560433f03b3087520aab0ae
