### ISSUE TITLE
Error when trying to run tutorial on TowardsDataScience

### ISSUE THREAD

**Issue by maiamarcelo** [mlr-org/mlr3proba#246]
After completing the installation, I almost got to have the first results, but stopped at the last step.

> bm <- benchmark(design)
INFO  [17:29:15.396] [mlr3] Running benchmark with 30 resampling iterations 
INFO  [17:29:15.412] [mlr3] Applying learner 'encode.scale.surv.coxtime.tuned' on task 'whas' (iter 2/3) 
INFO  [17:29:15.839] [bbotk] Starting to optimize 5 parameter(s) with '<OptimizerRandomSearch>' and '<TerminatorEvals> [n_evals=2, k=0]' 
INFO  [17:29:15.875] [bbotk] Evaluating 1 configuration(s) 
INFO  [17:29:15.919] [mlr3] Running benchmark with 1 resampling iterations 
INFO  [17:29:15.930] [mlr3] Applying learner 'surv.coxtime' on task 'whas' (iter 1/1) 
Error in .return_fail(msg = msg, error_on_fail) : 
  Dependency of 'cdf len x' failed.
This happened PipeOp surv.coxtime.tuned's $train()

Could I have any clue on how to go from here?

**Comment by maiamarcelo** [comment]
Thank you guys @mllg and @RaphaelS1 . I'll try to install the proper versions.

**Comment by RaphaelS1** [comment]
Finally fixed! Please install the latest versions of mlr3extralearners, mlr3proba and survivalmodels from GitHub and latest versions of distr6 and param6 from CRAN:

```R
install.packages(c("param6", "distr6"))
remotes::install_github("RaphaelS1/survivalmodels")
remotes::install_github("mlr-org/mlr3proba")
remotes::install_github("mlr-org/mlr3extralearners")
```
