### ISSUE TITLE
Fix distr6 bottleneck

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#25]
It is unclear if this issue should be opened here or in `distr6` as it only occurs as a result of predicting distributions but the problem lies in constructing multiple distributions. 

Simply put: say we have a trained Cox PH model and want to predict the survival distributions for 1,000 observations, then we have to construct 1,000 `WeightedDiscrete` distributions. Each of these runs through a series of validation checks, creates and updates a `ParameterSet` (PS), defines the d/p/q/r functions, and calls the parent class initializer.

This is clearly a long process that creates a huge bottleneck. One solution I have used to massively reduce the time for custom `Distribution`s is to include a private (undocumented) argument `.suppressChecks` that turns off all validation checks, it still takes time but is vastly quicker than without it. However, implementing this in every single `SDistribution` would take time and arguably encourages users to bypass important checks.

Another solution is to create a single instance of the `SDistribution` and then deep clone it 1,000 times, bypassing all checks. However, each contains its own `ParameterSet` which also needs to be deep cloned and then all of these need to be updated with the relevant values. This again decreases the bottleneck but with problems occurring from cloning.

So I am unsure the best solution...

**Comment by RaphaelS1** [comment]
As per offline conversation with @fkiraly earlier: this is a fault in the `VectorDistribution` in `distr6` and a fix is currently being written

**Comment by RaphaelS1** [comment]
Cox PH training and testing time for 300 observations reduced from 17 seconds to 0.3.

Thank you @fkiraly !!!

**Comment by fkiraly** [comment]
you're welcome
