### ISSUE TITLE
Stricter testing

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3proba#255]
These options should be set to get warnings for (unwanted) partial argument matching:

```r
options(
  warnPartialMatchDollar = TRUE,
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE
)
```
--> https://github.com/mlr-org/mlr3/blob/main/tests/testthat/setup.R and https://github.com/mlr-org/mlr3/blob/main/tests/testthat/teardown.R for an example.

Furthermore, https://github.com/mlr-org/mlr3/issues/781.

**Comment by bblodfon** [comment]
seems easy to do, this is still an issue in `mlr3proba` right @sebffischer @mllg ?

**Comment by bblodfon** [comment]
Tried this and it produces many warnings from downstream/other packages. As `mlr3extralearners` doesn't have it anymore, I will also not include this.
