### ISSUE TITLE
Fix bottleneck in parametric and flexible learners

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#26]
Similar to #25 except the problem here is that these are both formed from custom distributions and there is no way for a `VectorDistribution` to handle them without constructing them in construction of the `VectorDistribution`. I suspect however that there is no urgency to fix these as long as all others run quickly, this will just come down to 'slow run-time' in the benchmark process. Moreover, both aren't *too* slow because they have all checks suppressed. Still it should be dealt with in the future.

**Comment by fkiraly** [comment]
Hm, not sure whether I understand. Is it easy to write down a code example?

Generally, it might be best to avoid custom distributions in favour of parametric or non-parametric families?

**Comment by RaphaelS1** [comment]
For example a Cox PH model returns one `WeightedDiscrete` distribution for each observation. This is a pre-defined distribution, with defined d/p/q/r and other mathematical functions, that is constructed with given inputs and therefore inherits from `SDistribution`. However in the case of say a Weibull accelerated failure time model, then this is a `Distribution` object that is constructed with given d/p/q/r functions. Currently `VectorDistribution` only supports classes inheriting from `SDistribution` in the efficient version of the constructor that doesn't construct wrapped models. 

The only way I can see for `Distribution` objects to be passed to the `VectorDistribution` without constructing them would be to pass extra columns for all arguments...

Hmm. thinking about it now I have a better idea to solve this

**Comment by RaphaelS1** [comment]
Fit/predict for parametric models reduced from 3.2s to 0.28s for 500 observations
