### ISSUE TITLE
how to get the model and coefficient?

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [mlr-org/mlr3proba#260]
I just have another question: how to get the model and coefficient?
like you said before:
````
model = as.data.table(bmr)$learner[[8]]$model
model = bmr$resample_results$resample_result[[1]]$learners[[1]]$model
model = bmr$resample_result(1)$learners[[1]]$model
coef(bmr)
````
but the result is NULL.

**Comment by RaphaelS1** [comment]
Hi again I need a reprex to help sorry

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> Hi again I need a reprex to help sorry

reprex ？it's a package? https://cran.r-project.org/web/packages/reprex/index.html

**Comment by RaphaelS1** [comment]
A minimum reproducible example, some data and code that I can run myself https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jianguozhouzunyimedicaluniversity** [comment]
I @RaphaelS1 Sorry for this misunderstanding!
There are my codes.
````
# load packages
library("mlr3")
library("mlr3proba")
library("survival")
library(ggplot2)
library(ggfortify)
library("mlr3viz")
library("mlr3extralearners")
library(randomForestSRC)
# get datasets
data(peakVO2, package = "randomForestSRC")
dta <- peakVO2
obj <- rfsrc(Surv(ttodead,died)~., dta,
             ntree = 1000, nodesize = 5, nsplit = 50, importance = TRUE)
print(obj)
learners$model
# type = "right" is default
task.dta = as_task_surv(dta, id = "right_censored",
                        time = "ttodead", event = "died", type = "right")
print(task.dta)
learners = lrns(surv.coxph) 
bmr = benchmark(benchmark_grid(task.dta, learners, rsmp("cv", folds = 3)), store_models = TRUE)
````

**Comment by RaphaelS1** [comment]
No prob and thanks for providing that. For future reference this is a reprex for your question:

``` r
library("mlr3proba")
bmr = benchmark(
  benchmark_grid(tsk("rats"), lrn("surv.coxph"), rsmp("cv", folds = 3)),
  store_models = TRUE
)
bmr$resample_result(1)$learner$model
#> NULL
```

<sup>Created on 2022-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


As for the answer I've never actually used `store_models` before myself but this might actually be a bug. @mllg or maybe @be-marc could you confirm that `store_models` means that `learner$model` should not be `NULL`? Or have I misunderstood? Thanks!

**Comment by mllg** [comment]
Yes, if `store_models` is `FALSE`, we discard the model after predicting on the test set. The default is debatable, but without discarding the models, many users ran out of memory for certain models.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Thanks for your reply.
I add almost ML methods and try it again
````
worked.surv<-c("surv.akritas","surv.blackboost","surv.cforest","surv.coxph","surv.ctree",
"surv.gbm","surv.glmboost","surv.kaplan","surv.nelson","surv.obliqueRSF","surv.parametric",
"surv.penalized","surv.ranger","surv.rfsrc","surv.rpart")
learners = lrns(worked.surv) 
bmr = benchmark(benchmark_grid(task.dta, learners, rsmp("cv", folds = 3)), store_models = TRUE)
````
and successed.
````
INFO  [22:58:19.264] [mlr3] Running benchmark with 45 resampling iterations 
INFO  [22:58:19.268] [mlr3] Applying learner 'surv.ctree' on task 'right_censored' (iter 1/3) 
INFO  [22:58:20.788] [mlr3] Applying learner 'surv.obliqueRSF' on task 'right_censored' (iter 2/3) 
INFO  [23:00:06.389] [mlr3] Applying learner 'surv.penalized' on task 'right_censored' (iter 3/3) 
5
INFO  [23:00:07.117] [mlr3] Applying learner 'surv.kaplan' on task 'right_censored' (iter 2/3) 
INFO  [23:00:07.176] [mlr3] Applying learner 'surv.akritas' on task 'right_censored' (iter 2/3) 
INFO  [23:17:49.025] [mlr3] Applying learner 'surv.nelson' on task 'right_censored' (iter 2/3) 
INFO  [23:17:49.187] [mlr3] Applying learner 'surv.coxph' on task 'right_censored' (iter 3/3) 
INFO  [23:17:49.308] [mlr3] Applying learner 'surv.blackboost' on task 'right_censored' (iter 3/3) 
INFO  [23:17:54.122] [mlr3] Applying learner 'surv.akritas' on task 'right_censored' (iter 1/3) 
INFO  [23:35:47.548] [mlr3] Applying learner 'surv.rpart' on task 'right_censored' (iter 2/3) 
INFO  [23:35:47.893] [mlr3] Applying learner 'surv.kaplan' on task 'right_censored' (iter 1/3) 
INFO  [23:35:48.115] [mlr3] Applying learner 'surv.ctree' on task 'right_censored' (iter 3/3) 
INFO  [23:35:50.654] [mlr3] Applying learner 'surv.glmboost' on task 'right_censored' (iter 1/3) 
INFO  [23:35:55.854] [mlr3] Applying learner 'surv.rpart' on task 'right_censored' (iter 1/3) 
INFO  [23:35:55.934] [mlr3] Applying learner 'surv.ctree' on task 'right_censored' (iter 2/3) 
INFO  [23:35:59.569] [mlr3] Applying learner 'surv.ranger' on task 'right_censored' (iter 1/3) 
INFO  [23:36:35.655] [mlr3] Applying learner 'surv.parametric' on task 'right_censored' (iter 3/3) 
INFO  [23:36:38.489] [mlr3] Applying learner 'surv.nelson' on task 'right_censored' (iter 1/3) 
INFO  [23:36:38.567] [mlr3] Applying learner 'surv.penalized' on task 'right_censored' (iter 1/3) 
5
INFO  [23:36:39.049] [mlr3] Applying learner 'surv.rfsrc' on task 'right_censored' (iter 3/3) 
INFO  [23:36:44.415] [mlr3] Applying learner 'surv.gbm' on task 'right_censored' (iter 3/3) 
INFO  [23:36:44.590] [mlr3] Applying learner 'surv.penalized' on task 'right_censored' (iter 2/3) 
6
INFO  [23:36:45.300] [mlr3] Applying learner 'surv.gbm' on task 'right_censored' (iter 1/3) 
INFO  [23:36:45.502] [mlr3] Applying learner 'surv.parametric' on task 'right_censored' (iter 1/3) 
INFO  [23:36:46.999] [mlr3] Applying learner 'surv.obliqueRSF' on task 'right_censored' (iter 1/3) 
INFO  [23:38:59.722] [mlr3] Applying learner 'surv.gbm' on task 'right_censored' (iter 2/3) 
INFO  [23:39:00.033] [mlr3] Applying learner 'surv.cforest' on task 'right_censored' (iter 3/3) 
INFO  [23:39:45.209] [mlr3] Applying learner 'surv.nelson' on task 'right_censored' (iter 3/3) 
INFO  [23:39:45.289] [mlr3] Applying learner 'surv.coxph' on task 'right_censored' (iter 2/3) 
INFO  [23:39:45.433] [mlr3] Applying learner 'surv.cforest' on task 'right_censored' (iter 1/3) 
INFO  [23:40:37.682] [mlr3] Applying learner 'surv.parametric' on task 'right_censored' (iter 2/3) 
INFO  [23:40:38.440] [mlr3] Applying learner 'surv.rpart' on task 'right_censored' (iter 3/3) 
INFO  [23:40:38.510] [mlr3] Applying learner 'surv.rfsrc' on task 'right_censored' (iter 1/3) 
INFO  [23:40:43.117] [mlr3] Applying learner 'surv.ranger' on task 'right_censored' (iter 2/3) 
INFO  [23:41:15.736] [mlr3] Applying learner 'surv.glmboost' on task 'right_censored' (iter 2/3) 
INFO  [23:41:26.643] [mlr3] Applying learner 'surv.blackboost' on task 'right_censored' (iter 1/3) 
INFO  [23:41:33.587] [mlr3] Applying learner 'surv.akritas' on task 'right_censored' (iter 3/3) 
INFO  [23:59:10.893] [mlr3] Applying learner 'surv.glmboost' on task 'right_censored' (iter 3/3) 
INFO  [23:59:17.881] [mlr3] Applying learner 'surv.blackboost' on task 'right_censored' (iter 2/3) 
INFO  [23:59:56.393] [mlr3] Applying learner 'surv.ranger' on task 'right_censored' (iter 3/3) 
INFO  [00:00:43.522] [mlr3] Applying learner 'surv.obliqueRSF' on task 'right_censored' (iter 3/3) 
INFO  [00:05:57.925] [mlr3] Applying learner 'surv.kaplan' on task 'right_censored' (iter 3/3) 
INFO  [00:05:58.102] [mlr3] Applying learner 'surv.coxph' on task 'right_censored' (iter 1/3) 
INFO  [00:05:58.379] [mlr3] Applying learner 'surv.cforest' on task 'right_censored' (iter 2/3) 
INFO  [00:08:18.903] [mlr3] Applying learner 'surv.rfsrc' on task 'right_censored' (iter 2/3) 
Using 100 trees...

Using 100 trees...

Using 100 trees...

INFO  [00:08:54.793] [mlr3] Finished benchmark 
````
But the model still confused
````
model = bmr$resample_results$resample_result[[1]]$learners[[1]]$model
View(model)
````

I just checked the first one.
````
model

 Akritas Estimator 

Call:
  survivalmodels::akritas(data = data.table::setDF(task$data()),      time_variable = task$target_names[1L], status_variable = task$target_names[2L])

Response:
  Surv(time, status)
Features:
  {acei, age, angioten.II, anti.arrhy, anti.coag, aspirin, betablok, black, bmi, bun, cad, crcl, digoxin, dilver, diuretic.loop, diuretic.potassium.spar, diuretic.thiazide, glucose, hgb, insulin, interval, lipidrx.statin, lvef.metabl, male, niddm, nifed, nitrates, peak.rer, peak.vo2, q.wave.mi, resting.hr, resting.systolic.bp, smknow, sodium, surgery.aicd.implant, surgery.cabg, surgery.pacemaker, surgery.pci, vasodilator} 

````
<img width="907" alt="image" src="https://user-images.githubusercontent.com/20199977/160025576-2616df1a-c1d5-4b83-a8b0-90475647c695.png">

I can not get any coefficient for validation or put them in my MS.
Thanks!

**Comment by RaphaelS1** [comment]
> Yes, if `store_models` is `FALSE`, we discard the model after predicting on the test set. The default is debatable, but without discarding the models, many users ran out of memory for certain models.

Thanks @mllg 
But above I set `store_models = TRUE` and still got NULL for coxph

**Comment by RaphaelS1** [comment]
@jianguozhouzunyimedicaluniversity I'm still not sure what you're trying to do. What do you mean by coefficients? In the example you just gave the Akritas estimator is a conditional non-parametric estimator so doesn't have any coefficients. What do you mean by validation? Maybe you could link to a paper or a clear example online so we can help?

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @RaphaelS1 Thanks for your explanation. For non-parametric without coefficients is fine.
Eg. my last paper used lasso to identify LIPS model for patients treated with IO.
https://jitc.bmj.com/content/9/2/e001845
Right now, I need to use MLR3 survival analysis methods to select biomarker candidates. and validation in other cohorts.
By the way, for parametric methods, I need the final model or score.
![image](https://user-images.githubusercontent.com/20199977/160072951-86d7b127-cbe2-4560-b11d-b37bd53ee9c9.png)

Thanks!

**Comment by RaphaelS1** [comment]
In this case you definitely shouldn't be using `benchmark`. Benchmarking is to compare two or more models in order to get some form of generalisation guarantees for future predictions, i.e. you first compare some models, then decided which is the 'best' given the data, then retrain the best one, only then do you inspect the model (look at coefficients). 

So in your case you want to be using `lrn("surv.coxph")$train(task)$model`

**Comment by jianguozhouzunyimedicaluniversity** [comment]
I also like you said, need to find which method is best, in the next step is select which parameters are selected in both training and validation.

**Comment by mllg** [comment]
The resample result you extract from the benchmark result contains 3 trained learners. You are accessing the untrained (input) learner. To access the trained models, use the `$learners` slot instead:
```r
bmr$resample_result(1)$learners[[1]]$model
```

**Comment by RaphaelS1** [comment]
> You are accessing the untrained (input) learner.

Ooph confusing naming, I guess too late to change `learner` to `input_learner` and `learners` to `trained_learners`?

> I also like you said, need to find which method is best, in the next step is select which parameters are selected in both training and validation.

This isn't how benchmarking works. If you're looking to find optimal parameters from tuning then that's different,I also don't know what you mean by parameters selected in validation.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
I will try your code: 
````
bmr$resample_result(1)$learners[[1]]$model
````
And I also plan to choose the most important parameters according to all of the methods, I knew the non-parametric methods have the preference of each parameter, and we can merge the non-parametric methods' preference and the parametric methods' coefficient as "preference" to select which parameter is more important...

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> ,I also don't know what you mean by parameters selected in validation.
````
,I also don't know what you mean by parameters selected in validation.
````

This is validation of the model with those parameters and related coefficient.

eg. The validation cohort was classified using the same cut-off of LIPS into a low-risk group (n=29) and a high-risk group (n=4) ([figure 2D–F](https://jitc.bmj.com/content/9/2/e001845#F2)). The validation cohort confirmed the proposed risk model (C-index=0.71, 95% CI 0.62 to 0.81). The median OS in the low-risk and high-risk groups was 11.5 (95% CI 9.2 to 20.6) versus 3.7 (95% CI 2.8- NE) months (HR=0.30, 95% CI 0.10 to 0.91, p=0.024), respectively ([figure 3C](https://jitc.bmj.com/content/9/2/e001845#F3)).

**Comment by RaphaelS1** [comment]
> I knew the non-parametric methods have the preference of each parameter

This isn't correct. In your example above, the akritas estimator is simply the empirical CDF, there is no 'preference'

> and we can merge the non-parametric methods' preference and the parametric methods' coefficient as "preference" to select which parameter is more important

This doesn't make sense. Models calculate feature importance very differently so 'merging' them won't really help

> This is validation of the model with those parameters and related coefficient.

Right, I think what you mean is that you want to: 1) fit a model; 2) validate the model; 3) if the model is 'good' according to same validation then inspect the coefficients of the fitted model. Is that right? 


Sorry I'm doing my best to help but it's very unclear to me if this is a mlr3proba problem (e.g. a bug or we need a new feature) of the methodology is wrong. I wonder if it would be better to post on StackOverflow and then other people can also help?

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Thanks a lot!

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> Right, I think what you mean is that you want to: 1) fit a model; 2) validate the model; 3) if the model is 'good' according to same validation then inspect the coefficients of the fitted model. Is that right?

Totally right!
