### ISSUE TITLE
Add Breslow to distrcompositor

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#269]
```R
T = task$unique_times()
ht = numeric(length(T))
  for (i in seq_along(ht)) {
    di = sum(task$times() <= T[i] & task$status() == 1) # number of deaths
    ni = sum(exp(prediction$lp[task$times() > T[i]])) # number at risk
    ht[i] =  di / ni
  }
ht = cumsum(ht)
out = 1 - exp(-ht)
distr6::dstr("Matdist", cdf = matrix(out, nrow = length(p$lp), ncol = length(m3), TRUE, list(NULL, T)))
```

**Comment by adibender** [comment]
@RaphaelS1 @bblodfon late to the party, but shouldn't it be `== T[i]` in the nominator and `>= T[i]` in the denominator?

**Comment by bblodfon** [comment]
Hi @adibender, yes it is! Raphael had written a quick/preliminary implementation here, see [the code](https://github.com/mlr-org/mlr3proba/blob/HEAD/R/breslow.R#L137) and [documentation](https://mlr3proba.mlr-org.com/reference/breslow.html#details) we have implemented now.

**Comment by adibender** [comment]
@bblodfon Perfect, thx!
