### ISSUE TITLE
OOB with ranger: Error during tuning for TTE endpoints

### ISSUE THREAD

**Issue by MasterLuke84** [mlr-org/mlr3proba#275]
Hi Raphael,

I hope this is the right repo for this issue.

When using `oob_error` as performance measure for TTE endpoint with the `ranger` engine this error occurs: 

![image](https://user-images.githubusercontent.com/98314873/166219173-21d879bc-45cc-40a4-85ce-3e9dd6069401.png)

It works with regression/classification endpoints. 

# Example

```
library(mlr3)
library(paradox)
library(mlr3proba)
library(survival)

data("cancer")
data <- cancer %>% na.omit()

params <- ps(
  mtry =          p_int(lower = 1, upper = 3), 
  min.node.size = p_int(lower = 1, upper = 2), 
  num.trees =     p_int(lower = 50, upper = 100))

grid <- generate_design_lhs(params, n = 3)

mlr3tuning::tune(method       = "design_points", 
                 learner      = lrn("surv.ranger"), 
                 task         = as_task_surv(data, time = "time", event = "status",  id = "1111"), 
                 resampling   = mlr3::rsmp("cv", folds = 4), 
                 measures     = mlr3::msr("oob_error"), 
                 design       = grid$data, 
                 store_models = TRUE,
                 search_space = params)
```

Best regards

**Comment by RaphaelS1** [comment]
Thanks. It's breaking because of incompatible predict types, I might have to implement `surv.oob_error` to fix this.

**Comment by bblodfon** [comment]
@RaphaelS1 you can close this (fixed in https://github.com/mlr-org/mlr3/issues/816)
