### ISSUE TITLE
Problem when using surf.graf for surv.xgboost

### ISSUE THREAD

**Issue by MosquitoFan** [mlr-org/mlr3proba#284]
### Description

I used surv.xgboost for parameter tuning and use surf.graf as measures, 

My data composed of 1900 patients and12 features with survival time and event, here is the codes:

```
 train_task = TaskSurv$new("train",
                            backend = data.frame(train), time = "time",
                            event = "event")
  print(train_task)
  train_lrn <-  lrn("surv.xgboost", objective="survival:cox", nrounds=300L, eta=0.1)
  train_rsmp = rsmp("cv",folds = 5)
  set_threads(train_lrn, n = 16)
  set.seed(237)
  search_space = ps(surv.xgboost.max_depth = p_int(lower = 3L,upper = 18L),
                    surv.xgboost.gamma = p_dbl(lower = 0,upper = 9),
                    surv.xgboost.alpha = p_dbl(lower = 0,upper = 1),
                    surv.xgboost.lambda = p_dbl(lower = 0,upper = 1),
                    surv.xgboost.min_child_weight = p_int(lower = 1L,upper = 10L),
                    surv.xgboost.subsample = p_dbl(lower = 0.5,upper = 1),
                    surv.xgboost.colsample_bytree = p_dbl(lower = 0.5,upper = 1))
  evals = trm("evals", n_evals = 20)
  measure = msr("surv.graf")
  
  xgboost <- po("learner", learner = train_lrn)
  xgboost <- as_learner(xgboost)
  instance = TuningInstanceSingleCrit$new(task = train_task,
                                          learner = xgboost,
                                          resampling = train_rsmp,
                                          measure = measure,
                                          search_space = search_space,
                                          terminator = evals)
  
  tuner = tnr("grid_search", resolution = 5)
  opt_para = tuner$optimize(instance)
```

And I meet error as follows:

> Error in .__Archive__add_evals(self = self, private = private, super = super,  : 
  Assertion on 'ydt[, self$cols_y, with = FALSE]' failed: Contains missing values (column 'surv.graf', row 1).

I tried to change the resampling method like the fold of cv and from cv to boost but it doesn't work, and I tried to change the measures and the learners as follows:

**1. Change the measures**
Measures like surv.cindex, surv.hung_auc, surv.uno_auc can run the code.

But the surv.calib_alpha, surv.intlogloss, surv.nagelk_r2, surv.oquigley_r2 meet the same error;
the surv.chambless_auc, surv.song_auc meet the follow error:

> Error in FUN(lpnew = prediction$lp, Surv.rsp = c(6092, 469, 567, 2152,  : 
  argument "lp" is missing, with no default

and the measures of tnr and tpr meet the following error:

> Error in .__MeasureSurvSongTNR__.score(self = self, private = private,  : 
  `times` must be non-NULL

**2. Change the learners**

I changed the lrn to rfsrc and the surv.graf can be used, so I think my data have no problem.

```
  train_lrn <- lrn("surv.rfsrc")
  train_rsmp = rsmp("cv",folds = 5)
  set_threads(train_lrn, n = 16)
  set.seed(237)
  search_space = ps(ntree = p_int(lower = 100L, upper = 2000L),
                    nodesize = p_int(lower = 5L, upper = 80L),
                    mtry = p_int(lower = 4L, upper = 8L),
                    splitrule = p_fct(c("logrank", "logrankscore")))
  evals20 = trm("evals", n_evals = 20)
  measure = msr("surv.graf")
  
  instance = TuningInstanceSingleCrit$new(task = train_task,
                                          learner = train_lrn,
                                          resampling = train_rsmp,
                                          measure = measure,
                                          search_space = search_space,
                                          terminator = evals20)
  
  tuner = tnr("grid_search", resolution = 5)
  opt_para = tuner$optimize(instance)
```
**Possible reason**
I am not sure is the surv.xgboost does not support _prediction: distr_? Beacuase all measures need the distr meet the same error. 

I know the xgboost package, where surv.xgboost from, doesn't have function for calculating a matrix of predicted survival probabilities, and there is a _survXgboost_ package that can output a matrix of predicted survival **Possible reason** for xgboost . But I don't know how to added this function into mlr3.

**New learner from survXgboost package**

I tried to set a new learner to get the matrix of predicted survival probabilities.

The package location of mlr3extralearners is C:/Users/ziwen/Documents/R/win-library/4.1/mlr3extralearners

Then I use create_learner(）function as follows,

```
create_learner(
  pkg = "C:/Users/ziwen/Documents/R/win-library/4.1/mlr3extralearners",
  classname = "SXgboost",
  algorithm = "xgboost",
  key = "SXgboost",
  type = "surv",
  package = "survXgboost",
  caller = "xgb.train.surv",
  feature_types = c("integer", "numeric"),
  predict_types = c("crank", "lp", "distr"),
  properties = c("weights", "missings", "importance"),
  references = TRUE,
  gh_name = "MosquitoFan"
)
```
The learner file is in the attachment.

When I test with 

`install_learners("surv.SXgboost")`

I meet the error

`Error: Element with key 'surv.SXgboost' not found in DictionaryLearner! Did you mean 'surv.xgboost' / 'surv.coxboost' / 'surv.gamboost'?`

So I also experienced a rough time creating the new learner T.T

**Last but not least**
If it is because lacking function for calculating distr, could you please tell me how to add it to surv.xgboost learner?
I want to use surv.graf to train surv.xgboost and thanks for your help!

Best,
Ziwen

### Reproducible example

Sorry I don't have examples
[learner_survXgboost_surv_sxgboost.zip](https://github.com/mlr-org/mlr3proba/files/9079927/learner_survXgboost_surv_sxgboost.zip)
.

**Comment by RaphaelS1** [comment]
Hey you have way too many issues here for me to be able to help in one Issue. And without a reprex I can't begin to debug. Please cleanly separate out individual issues/questions you have and include a reproducible example that demonstrates the problem.

**Comment by realreal2020** [comment]
I have encountered the same problem. Could you share the solution, if appropriate?

**Comment by RaphaelS1** [comment]
@realreal2020 can you elaborate what problem?
