### ISSUE TITLE
Add support for non-right-censored data

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#29]
Currently the survival task constructor allows specification of the survival time and status, assuming right-censoring and whilst this is certainly the case in the majority of survival tasks it is not the only case. Therefore I propose updating the survival task to be in line with the `Surv` object, i.e.

```R
TaskSurv$new(id, backend, time, status, time2, type=c('right', 'left', 'interval', 'counting', 'interval2', 'mstate'), origin = 0
```

To be more in line with `Surv` perhaps change the arg `status` to `event`. As this is all passed directly to a `Surv` object I don't see any reason why we can't increase the construction flexibility.

**Comment by fkiraly** [comment]
I agree to this - as long as there is no reason to diverge, variable names and annotations should be compatible between the survival task and `Surv` objects.

The discussion also touches a more general points: many advanced learning tasks will require a data model where non-primitive data types are stored in columns or tables. 

The `Surv` object is a crutch, if you will, to allow storage of an advanced data type - censored continuous valued data. A single `Surv` object corresponds to a single data frame column that is "censored continuous" valued, i.e., a column vector with "censored continuous" valued entries.

This kind of situation appears in survival a second time, in making individual risk predictions: if we return a distr object as a prediction, this is also a column, now distribution valued.

The general question is: how should mlr3, eventually, represent non-primitive data in columns? Through back-ends, tasks, etc. The answer is perhaps not as obvious as in languages where you can put arbitrary types, in a queriable way, into columns or composites (such as structs).

The question will, though, arise invariably when going beyond the tabular case with primitive types.

**Comment by RaphaelS1** [comment]
Added, the only change made to the `Surv` object is that I have reversed the order of `time2` and `event` for more intuitive passing of arguments
