### ISSUE TITLE
Broken link on the pkgdown website

### ISSUE THREAD

**Issue by mikolajsp** [mlr-org/mlr3proba#290]
### Description

On the [website](https://mlr3proba.mlr-org.com/) documenting the mlr3proba package, the vignette links are broken.

They lead to: 
- `https://mlr3book.mlr-org.com/special-tasks.html#survival` and
- `https://mlr3book.mlr-org.com/special-tasks.html#density`,
whereas they should to
- `https://mlr3book.mlr-org.com/special.html#survival` and
-  `https://mlr3book.mlr-org.com/special.html#density`

Edit: this is true for both development and release versions of the website

**Comment by RaphaelS1** [comment]
Thanks, closed in https://github.com/mlr-org/mlr3proba/commit/0132fa2a891788774dcf9bc150f322301dfb6a47
