### ISSUE TITLE
mlr3proba not availabe on CRAN

### ISSUE THREAD

**Issue by MasterLuke84** [mlr-org/mlr3proba#291]
### Description

Dear Raphael,

currently it seems that `mlr3proba` is not available on CRAN (same for `distr6`, `param6`, `set6`).

Nevertheless, I tried to install version 0.4.4 via devtools. For this I had to install above mentioned packages manually as well (via devtools). During installation of `mlr3proba` following error occured: 

![image](https://user-images.githubusercontent.com/98314873/186858103-833e3771-1e9d-47ff-acd9-bc2d06ed8a4a.png)

Thanks for your help in advance!

### Reproducible example

`devtools::install_version("mlr3proba", "0.4.4") `

**Comment by RaphaelS1** [comment]
Hi mlr3proba is archived on CRAN and likely won't be back up. Please try the following (I'm working on simplifying slightly):

```R
options(repos=c(
  mlrorg = 'https://mlr-org.r-universe.dev',
  raphaels1 = 'https://raphaels1.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'
))
install.packages("mlr3proba")
```

or

```R
install.packages("distr6", repos = "https://raphaels1.r-universe.dev")
install.packages("mlr3proba", repos = "https://mlr-org.r-universe.dev")
```

**Comment by MasterLuke84** [comment]
Hi Raphael,

thank you for your answer. 
Your suggestion will install the newest version of mlr3proba, but with this version some prediction scores like `intlogoss` or `schmid` would fail. That is the reason, why I would like to install v0.4.4. 

But I guess I found the issue: 

It might be related to the `mlr3proba:::weighted_survival_score()` function call. The issue occurs during `assert_matrix(cdf, nrows = length(unique_times), ncols = length(true_times),  any.missing = FALSE)` .  Due to the previous condition how the `cdf` is obtained

![image](https://user-images.githubusercontent.com/98314873/186927140-a528e6e7-b35d-4858-8f2d-5d864c8060af.png)

the `if` and `else clause` will differ in different dimensions for `cdf`. Hence, the `cdf = as.matrix(distribution$cdf(unique_times))` should be transposed  to be consistent with the cdf-matrices that are composed by the `else`-clause, if I get it right.

**Comment by RaphaelS1** [comment]
That's strange I'm pretty sure we fixed that bug..... I'll need to look into this more. What version of distr6 do you have installed?

**Comment by MasterLuke84** [comment]
I re-installed `distr6` (v1.6.11) and now it works. Maybe I had a former version installed. Thanks for your help.
May I ask, why `mlrproba` is not likely to be back up on CRAN again?

**Comment by RaphaelS1** [comment]
Sure, see here https://twitter.com/RaphaelS101/status/1506321623250571265

**Comment by RaphaelS1** [comment]
Updated dependency here https://github.com/mlr-org/mlr3proba/commit/f89a81995ed7e5be97fba5d38948a620a4d7925f

**Comment by dpryan79** [comment]
Can you tag version 0.4.10 or whatever version you want to include these fixes? I'm updating the feedstock on conda-forge and will redirect it to github rather than cran so new versions are automatically picked up. But that only works with tagged releases :)

**Comment by RaphaelS1** [comment]
https://github.com/mlr-org/mlr3proba/releases/tag/v0.4.13 thanks
