### ISSUE TITLE
Move lp to method, return crank and distr only

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#30]
From discussions with @mllg and @fkiraly we agreed the following:

* A survival task prediction object will return `crank` and `distr` only
* `distr` will only be returned if this is a return type of the learner, and we will not have a default compositor in the learner (with the exception of `parametric` and `flexible`, which are defined in `mlr3proba`)
* `crank` is some sort of continuous relative ranking/risk. There is no specific definition for all learners but it will be well documented how it is computed by the learner.
* The `lp` return type will instead be moved to a public method, which is accessible by any compositors that require it

**Comment by RaphaelS1** [comment]
Okay I'm now questioning having `lp` as a method (public or active). Essentially to do so would involve having the learners predict an `lp` return type and then storing this in a private method and returning it using an active method. But this would lose the ordering and other checks involved with having it in the `Prediction` object. I think a better solution is simply to return whichever of `lp` `risk` and `distr` can be returned natively from the learners, as this is simplest to document (and yes we could consider going back to `risk` from `crank` as this is the term used in all learners)

**Comment by fkiraly** [comment]
I'm not strongly opposed to `lp` as a return type, as long as it's clear in the design that a general method won't have this (only GLM). The "bad" alternative is that users think they should implement this, or other parts of architecture assume it's returned, even if you are not dealing with a GLM.

**Comment by RaphaelS1** [comment]
Agreed. We ensure documentation and extension guidelines are precise but keep `lp` as a return type
