### ISSUE TITLE
cleanup after unloading

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3proba#301]
After unloading `mlr3proba` I think the dictionary items that were added by proba should be removed again. 
I made a similar PR here already: https://github.com/mlr-org/mlr3learners/pull/258

**Comment by RaphaelS1** [comment]
Could you copy that PR here?

**Comment by jemus42** [comment]
This would require to undo everything done in `.onLoad` here https://github.com/mlr-org/mlr3proba/blob/930d8b0a3b460ef8286d53670a4389fdd241bfe7/R/zzz.R#L41-L173

Somewhat cumbersome and unfortunately not easily automatable as far as I can tell, maybe it would be even worth considering some generalized machinery for this in mlr3misc maybe?

**Comment by bblodfon** [comment]
Yep, we can definitely compress all this for sure, asked @sebffischer for help
