### ISSUE TITLE
Bug in RCLL

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3proba#311]
Hi Raphael,

I stumbled across this bug related to the Right-censored Log-Loss (RCLL) measure - I think the issue is when there are no censored observations in the test set then the calculation fails, see below:

``` r
library(mlr3verse)
#> Loading required package: mlr3
library(mlr3proba)

set.seed(0)
taskv = as_task_surv(x = survival::veteran, id = 'veteran',
  time = 'time', event = 'status')
poe = po('encode')
taskv = poe$train(list(taskv))[[1L]]

sum(taskv$truth()[,2] == 0) # few censored patients
#> [1] 9

learner = lrn('surv.ranger', verbose = FALSE,
  id = 'SurvivalForestLogRank',
  label = 'Random Forest (Logrank splitrule)',
  fallback = lrn('surv.kaplan'),
  num.threads = 4,
  splitrule = 'logrank',
  num.trees = 50,
  mtry.ratio = 0.8,
  min.node.size = 3,
  importance = 'permutation'
)
#> Warning: The fallback learner 'surv.kaplan' and the base learner
#> 'SurvivalForestLogRank' have different predict types: 'crank' != 'distr'.

rcll = msr('surv.rcll')

grid = benchmark_grid(tasks = taskv, learners = learner,
  resamplings = rsmp('cv', folds = 6))
grid
#>              task                 learner         resampling
#> 1: <TaskSurv[55]> <LearnerSurvRanger[38]> <ResamplingCV[20]>
bm = benchmark(design = grid, store_models = TRUE)
#> INFO  [01:04:44.374] [mlr3] Running benchmark with 6 resampling iterations
#> INFO  [01:04:44.455] [mlr3] Applying learner 'SurvivalForestLogRank' on task 'veteran' (iter 1/6)
#> INFO  [01:04:44.555] [mlr3] Applying learner 'SurvivalForestLogRank' on task 'veteran' (iter 2/6)
#> INFO  [01:04:44.620] [mlr3] Applying learner 'SurvivalForestLogRank' on task 'veteran' (iter 3/6)
#> INFO  [01:04:44.707] [mlr3] Applying learner 'SurvivalForestLogRank' on task 'veteran' (iter 4/6)
#> INFO  [01:04:44.781] [mlr3] Applying learner 'SurvivalForestLogRank' on task 'veteran' (iter 5/6)
#> INFO  [01:04:44.871] [mlr3] Applying learner 'SurvivalForestLogRank' on task 'veteran' (iter 6/6)
#> INFO  [01:04:44.942] [mlr3] Finished benchmark
dt = as.data.table(bm)

for(p in dt$prediction) {
  print(sum(p$truth[,2] == 0)) # censored individuals
  print(p$score(rcll))
}
#> [1] 2
#> surv.rcll 
#>  25.11288 
#> [1] 2
#> surv.rcll 
#>  30.28606 
#> [1] 0
#> Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), : 'data' must be of a vector type, was 'NULL'

# So the following two also fail
bm$score(rcll)
#> Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), : 'data' must be of a vector type, was 'NULL'
bm$aggregate(rcll)
#> Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), : 'data' must be of a vector type, was 'NULL'
```

<sup>Created on 2023-02-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by RaphaelS1** [comment]
I don't know if this is a bug? If there's no censoring then you shouldn't be using survival analysis really

**Comment by bblodfon** [comment]
My arguments for why this is a bug would be:
- Every other measure tested in #312 provides a meaningful score even in the extreme case where all observations are censored (or the reverse), so shouldn't RCLL work in these cases as well?
- From the [mathematical formula](https://mlr3proba.mlr-org.com/reference/mlr_measures_surv.rcll.html), it seems easy to see what happens when Δ=0 or 1 for all observations in the test set. This is what happened in the example above, i.e. in this code [line](https://github.com/mlr-org/mlr3proba/blob/HEAD/R/MeasureSurvRCLL.R#L71), `truth[!event, 1]` becomes `NULL` since for every subject Δ=1. Two simple checks in the code would solve this issue, want me to do a PR?
- In the example with the veteran survival dataset, there is minimal censoring, which results in a test set of the CV resampling to have no censored subjects. That is not true of course for the whole dataset, so I think we should be using survival analysis :)

**Comment by RaphaelS1** [comment]
Ah okay. Yes I agree, we definitely need to be able to handle the case if a test set has no censoring - I was thinking more about training. A PR would be great, thanks

**Comment by RaphaelS1** [comment]
I'd recommend handling the edge cases with an `if` statement, so `if(all censored) do x elseif(all died) do y else do z`

**Comment by bblodfon** [comment]
Small questions: 

1) I see there is this parameter `eps` in some measures to avoid situations where you have to take the `log` or divide by zero. In some measures it is defined by default as `1e-3` (C-index, Graf score, ...) and in others (IntLogLoss, RCLL) as `1e-15`. Is there a specific reason why these are set to different defaults?

2) Was writing some tests and came across the following behavior. It seems that `truth()` does not return the proper row order after filtering the task:
``` r
library(mlr3proba)
#> Loading required package: mlr3

set.seed(1)
t = tsk("rats")$filter(sample(1:300, 50))

# first 6 rows
t$data(rows = 1:6)
#>    time status litter rx sex
#> 1:  101      0      1  1   f
#> 2:   49      1      1  0   f
#> 3:  104      0      1  0   f
#> 4:   91      0      2  1   m
#> 5:  104      0      2  0   m
#> 6:  102      0      2  0   m

# shouldn't it be the first 6 rows?
head(t$truth())
#> [1] 104+ 104+  97+  91+  89+ 104+

# the first 6 rows
t$truth(rows = 1:6)
#> [1] 101+  49  104+  91+ 104+ 102+

head(t$data(rows = NULL))
#>    time status litter rx sex
#> 1:  104      0      5  1   f
#> 2:  104      0      5  0   f
#> 3:   97      0      7  0   f
#> 4:   91      0      8  1   m
#> 5:   89      0      9  1   f
#> 6:  104      0     10  0   m
```

<sup>Created on 2023-02-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think that `$data(rows = NULL)` is the [culprit](https://github.com/bblodfon/mlr3proba/blob/main/R/TaskSurv.R#L93)

**Comment by bblodfon** [comment]
Opened mlr-org/mlr3#896 for the (2)
