### ISSUE TITLE
ROC AUC's parametes not initiliazed correctly

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3proba#315]
I think the following issue relates to all measures that inherit the `MeasureSurvAUC` class:

``` r
library(mlr3proba)
#> Loading required package: mlr3

uno_auc = msr('surv.uno_auc', integrated = FALSE)
uno_auc$param_set$values$integrated # TRUE
#> [1] TRUE

uno_auc = msr('surv.uno_auc', times = 100)
uno_auc$param_set$values$times # NULL
#> NULL

uno_auc$param_set$values$times = 100 # now it takes it
uno_auc
#> <MeasureSurvUnoAUC:surv.uno_auc>
#> * Packages: mlr3, mlr3proba, survAUC
#> * Range: [0, 1]
#> * Minimize: FALSE
#> * Average: macro
#> * Parameters: integrated=TRUE, times=100
#> * Properties: requires_task, requires_train_set
#> * Predict type: lp
#> * Return type: Score
```

<sup>Created on 2023-02-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bblodfon** [comment]
Hi @RaphaelS1,

This turned out easy to fix (see https://github.com/mlr-org/mlr3proba/pull/314 - could you please check the PR?) - I just followed how the other AUC's measures were initialized. But I don't understand it! For example, in the `surv.graf` measure, how is it possible that the parameters are assigned in the following snippet, when the initialization is as in the [following code](https://github.com/mlr-org/mlr3proba/blob/HEAD/R/MeasureSurvGraf.R#L63)? (e.g. where do the `integrated` and `times` values get overwritten?)
``` r
  library(mlr3proba)
#> Loading required package: mlr3
  m = msr("surv.graf", integrated = FALSE, times = 100)
  m$param_set$values$integrated
#> [1] FALSE
  m$param_set$values$times
#> [1] 100
```

<sup>Created on 2023-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by RaphaelS1** [comment]
Ah that all happens in the primary mlr3 interface

**Comment by bblodfon** [comment]
I was trying to find exactly where, even went as back as `mlr3::Measure`, but really I couldn't get it!
