### ISSUE TITLE
Suggestions: RCLL range and ERV measures properties

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3proba#323]
Hi,

1. Is RCLL's [range](https://github.com/mlr-org/mlr3proba/blob/main/R/MeasureSurvRCLL.R#L51) correct? From it's [formula](https://mlr3proba.mlr-org.com/reference/mlr_measures_surv.rcll.html), I would guess `[0, Inf]`?
2. For every measure initialized with `ERV = TRUE` (they are all currently losses), we should also change its properties `minimize` (from `TRUE` to `FALSE`) and `range` (to `[-Inf, 1]` => 0 means same performance as Kaplan-Meier, negative values worse, positive values better than KM and 1 is the absolute possible maximum for ERV measures).

**Comment by RaphaelS1** [comment]
1. Good catch! Technically the upper limit actually depends on the `eps` parameter so with the default it's [0, 34.53878] but ignoring that yes it's [0, Inf)
2. Also good catch!! 

Can I convince you to PR these changes?

**Comment by bblodfon** [comment]
> Can I convince you to PR these changes?

Yes, no prob, just wanted to make sure!
