### ISSUE TITLE
Inability to install mlr3proba

### ISSUE THREAD

**Issue by rpgately** [mlr-org/mlr3proba#325]
Hi Raphael,

I am having trouble installing this package on an m1 mac, RStudio Version 2023.03.0+386, R version 4.1.2 , reprex attached below. Have also tried the different methods of installation suggested on the github with similar errors. I have tried to install the dependencies set6 and distr6 separately but I get a similar error when I try to install those,

Any advice would be very much appreciated,

Many thanks in advance,

Ryan 

options(repos=c(
  mlrorg = 'https://mlr-org.r-universe.dev',
  raphaels1 = 'https://raphaels1.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'
))
install.packages("mlr3proba")
#> also installing the dependencies 'set6', 'distr6'
#> 
#>   There are binary versions available but the source versions are later:
#>           binary source needs_compilation
#> set6       0.2.4  0.2.5              TRUE
#> distr6     1.6.9 1.6.15              TRUE
#> mlr3proba  0.4.9  0.5.2              TRUE
#> installing the source packages 'set6', 'distr6', 'mlr3proba'
#> Warning in install.packages("mlr3proba"): installation of package 'set6' had
#> non-zero exit status
#> Warning in install.packages("mlr3proba"): installation of package 'distr6' had
#> non-zero exit status
#> Warning in install.packages("mlr3proba"): installation of package 'mlr3proba'
#> had non-zero exit status
Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by RaphaelS1** [comment]
Does `remotes::install_github("mlr-org/mlr3proba")` work? I tested yesterday on an M1 mac without problem

**Comment by rpgately** [comment]
no this is the error when I do that (below) , from googling it it seems like it may be something to do with xcode and openMP? will see if I can download those

devtools::install_github("mlr-org/mlr3proba")
#> Downloading GitHub repo mlr-org/mlr3proba@HEAD
#> Error: Failed to install 'mlr3proba' from GitHub:
#>   Could not find tools necessary to compile a package
#> Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by RaphaelS1** [comment]
What happened when you called `pkgbuild::check_build_tools(debug = TRUE`?

**Comment by rpgately** [comment]
exact same error again. 

> pkgbuild::check_build_tools(debug = TRUE)
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by RaphaelS1** [comment]
After some googling looks like it might be an issue on your end with Rtools. Possibly due to these packages using Rcpp

https://stackoverflow.com/questions/66359031/install-with-devtoolsinstall-github-fails-to-detect-build-tools

https://github.com/r-lib/pkgdown/issues/377

https://github.com/r-lib/devtools/issues/2033

**Comment by rpgately** [comment]
Hi Raphael - the stackoverflow suggestion worked thanks so much! essentially involved downloading Xcode, homebrew and updating a base R folder (Makevars). Obviously was more of an R issue than anything to do with mlr3proba but I am very grateful for your help,

Ryan
