### ISSUE TITLE
The problem of imbalanced survival data

### ISSUE THREAD

**Issue by lzxcvn** [mlr-org/mlr3proba#369]
Greetings,

I am planning to conduct survival analysis for early-stage lung cancer. My challenge is the extreme imbalance in my dataset, with very few events having outcomes. The confusion arises because the usual balance adjustment methods in data preprocessing, such as SMOTE, do not seem directly applicable to survival tasks. Is there any algorithm or method suited for addressing imbalance in survival analysis?

**Comment by bblodfon** [comment]
Hi! In the case of datasets with high-degree of censoring, it's usually up to model used how to best deal with it. Having said that, there are (experimental) preprocessing ways to translate the survival task to a regression one, have a look at this [pipeline](https://mlr3proba.mlr-org.com/reference/mlr_graphs_survtoregr.html) we have.

**Comment by lzxcvn** [comment]
@bblodfon Thank you for your response. My research aims to utilize various survival analysis learners to develop predictive models. However, survival learners, such as surv.arosf and surv.akritas, which are designed for predicting 5-year survival rates, appear distinct from typical regression learners. These specific learners do not seem to fall under the conventional regression category. For survival data characterized by a significant number of censored observations, addressing this challenge seems quite complex.

**Comment by bblodfon** [comment]
Let me know if you want any help in particular with something related to this package, this question seems more broad and you could ask on stackexchange or stackoverflow for more/better directions.
