### ISSUE TITLE
About feature selection in mlr3proba

### ISSUE THREAD

**Issue by DingfanGuo** [mlr-org/mlr3proba#373]
Could you please tell me how to do feature selection on survival data in mlr3proba? I have checked the official documentation and there seems to be no example where this is discussed. Any suggestions please, thanks!

**Comment by bblodfon** [comment]
Hi! It's in my plans to write a short mlr3 gallery post on that, but to get you started:
- Read the [feature selection chapter](https://mlr3book.mlr-org.com/chapters/chapter6/feature_selection.html) in the mlr3 book, many of the examples *play* with survival models as well
- Use either `mlr3fselect` or `mlr3filters` (you can use survival-specific filters in the second one, see [here](https://mlr3filters.mlr-org.com/index.html#implemented-filters), or task-agnostic)

**Comment by DingfanGuo** [comment]
> Hi! It's in my plans to write a short mlr3 gallery post on that, but to get you started:
> 
> * Read the [feature selection chapter](https://mlr3book.mlr-org.com/chapters/chapter6/feature_selection.html) in the mlr3 book, many of the examples _play_ with survival models as well
> * Use either `mlr3fselect` or `mlr3filters` (you can use survival-specific filters in the second one, see [here](https://mlr3filters.mlr-org.com/index.html#implemented-filters), or task-agnostic)
> 
> The whole idea is that feature selection is done by other packages not `mlr3proba`. If things don't work when using some kind of filters, post on stackoverflow as it might be a different person than me who can help you with that!

Thanks for your suggestions !
