### ISSUE TITLE
mlr3 proba missing from CRAN

### ISSUE THREAD

**Issue by benjaminjohansen** [mlr-org/mlr3proba#379]
Get this error when trying to check the package out on CRAN:

**
Please use the canonical form https://cran.r-project.org/package=mlr3proba to link to this page.)

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-05-16_check_results_mlr3proba.html).

Archived on 2022-05-16 as check issues were not corrected in time.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/mlr3proba).

[](Package ‘mlr3proba’ was removed from the CRAN repository.

**

**Comment by bblodfon** [comment]
hi @benjaminjohansen , please read here => https://github.com/mlr-org/mlr3proba?tab=readme-ov-file#installation.
