### ISSUE TITLE
Unable to install mlr3proba

### ISSUE THREAD

**Issue by sfgrey** [mlr-org/mlr3proba#422]
Attempted to install the mlr3proba package using "install.packages("mlr3proba", repos = "https://mlr-org.r-universe.dev")" and received the following error:

Error in match.arg(type, c("binary", "source")) : 
  'arg' should be one of “binary”, “source”
In addition: Warning messages:
1: In value[[3L]](cond) : Could not find any credentials
2: In value[[3L]](cond) : Could not find any credentials
3: In value[[3L]](cond) : Could not find any credentials

**Comment by bblodfon** [comment]
Hi @sfgrey , I have verified that this installation works... maybe it's something on your side (I see something about credentials)? Can you try to install the development version using the below command?
```
devtools::install_github("mlr-org/mlr3proba")
```

**Comment by sfgrey** [comment]
Hi John,

I was able to obtain the package using

install.packages("mlr3proba", repos = "https://mlr-org.r-universe.dev")

The issue was a corrupted renv.lock file that would not let me change the repos.

Thanks,
Scott
________________________________
