### ISSUE TITLE
User-test survAUC measures

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#43]
Some measures caused the R bomb, need to diagnosis cause of this.
Also need to decide what to do with measures that return multiple results (e.g. non-integrated AUC over multiple time-points)

**Comment by fkiraly** [comment]
Sorry, I don't understand the term "R bomb" here - I assume it's some programmer slang, but a google search tells me it's synonymous to "ghosting" in a dating context, which is probably not what you mean.

**Comment by RaphaelS1** [comment]
Haha no, I mean this:

https://i2.wp.com/lh3.googleusercontent.com/-IzfBppQwNQI/WAUEsgJwmnI/AAAAAAAAAXU/9aG6xKFRxY8/rstudio-bomb.png?w=450&ssl=1

**Comment by fkiraly** [comment]
Oooohhhh, that bomb (which I know well).

**Comment by fkiraly** [comment]
Which measures?

**Comment by RaphaelS1** [comment]
The problem is the `survAUC` implemented measures when integrated is turned off. `mlr3` supports single returns, i.e. a single score. So I am debating whether to force users to either select between using integrated versions (which by definition return one score) or to supply a single time-point to evaluate the score. Alternatively, multiple scores could be returned as a list but I have a feeling this will cause problems with interfacing other parts of the API

**Comment by RaphaelS1** [comment]
BTW this also raises the question of if we should have non-integrated versions of Graf and log-loss where the user can supply a single time-point, might make sense for nice visualisation

**Comment by fkiraly** [comment]
I see - similiar issues might occur if you want:
- post-hoc analyses of benchmark results
- visualizations of evaluation statistics
- complex quantifiers such as confusion matrices

It might be worth looking at how these are solved architecturally at the moment.
"confusion matrix" is perhaps the most relevant precedent, if exists.

**Comment by RaphaelS1** [comment]
`MeasureClassifConfusion` cleverly gets around this by actually defining 18 measures that pull the single responses (e.g. tp, tn, tpr, etc.) from the confusion matrix

**Comment by RaphaelS1** [comment]
It wouldn't be hard to add a wrapper around `MeasureClassifConfusion` that creates an actual matrix, similarly one for measures at time points that pulls multiple times from the measure, but this is both inefficient and messy

**Comment by fkiraly** [comment]
>MeasureClassifConfusion cleverly gets around this by actually defining 18 measures

Conscious that this might draw the ire of the authors to this thread, this sounds more like abuse-of-interface, of an interface not designed to support complex (here: multivariate) return types?

**Comment by fkiraly** [comment]
The problem for the scores-by-cut-off being that the number of cut-off points is, or scales with, the number of test points, which would mean the measures would have to be generated on-the-fly, which sounds even more terrible as an abuse of interface.

**Comment by RaphaelS1** [comment]
Well bear in mind that the survAUC measures support supplying times in the argument so only the requested times calculated, otherwise can be selected post-hoc if returning as matrix

**Comment by RaphaelS1** [comment]
I disagree about the confusion matrix being a bad design choice. If you imagine a benchmark object with a column of scores, then clearly only single aggregates scores can be read and understood well

**Comment by fkiraly** [comment]
yes, I now think you are right - as long as specifying and computing multiple measures simultaneously is supported by the interface.

I just wanted to have another look at how this is solved for the confusion, and I (and google, apparently) remember it being in MeasureClassifConfusion, but I can't find it anymore - do you know where it went?

**Comment by RaphaelS1** [comment]
It appears to have gone [here](https://github.com/mlr-org/mlr3/blob/master/R/PredictionClassif.R)... I'm slightly confused myself now !

**Comment by fkiraly** [comment]
?? it's no longer a measure?
Perhaps @mllg can shed light on this?

**Comment by RaphaelS1** [comment]
Okay, after a lot of testing and iterating, the only conclusion I can find is that the problem lies in the `survAUC` package itself. For no clear reason, at times the same function will work and at others R will encounter a fatal error. Unsure how to proceed here, do we remove all `survAUC` functions, or just hope error won't affect users?

**Comment by mllg** [comment]
> ?? it's no longer a measure?
> Perhaps @mllg can shed light on this?

We switched from class `MeasureClassifConfusion` (which was slighty abused to calculate all the ROC-related measures) to just interfacing functions in `mlr3measures`. I'm not sure I completely understood your discussion here, but here are some points which might be relevant for this issue:

1. You can still retrieve a confusion matrix by accessing `PredictionClassif$confusion`.
3. I also had some troubles with `survAUC`. I'll send you the conversation I had with the package authors via slack.

**Comment by fkiraly** [comment]
Aah, it just moved to a different repository - which is the point I didn't realize - and in addition exists as an inbuilt scorer to the classif prediction object (rather than, as I thought, the latter entirely replacing the original, which would be pretty odd).

Here it is, @RaphaelS1 :
https://github.com/mlr-org/mlr3measures/tree/master/R
https://github.com/mlr-org/mlr3measures/blob/master/R/confusion_matrix.R

**Comment by fkiraly** [comment]
>Unsure how to proceed here, do we remove all survAUC functions, or just hope error won't affect users?

We could just write our own? It's not that the formulae are extremely arcane. Perhaps even better for transparency?

**Comment by fkiraly** [comment]
I would even go so far to argue that there should be no external dependencies whatsoever in core functionality related to validity checks and success control - as external dependencies are always, in-principle, a risk.

Translating a key "kernel security" principle, replacing the word "security" with "algorithmic validity". I.e., even if you want to have lots of dependencies, apps, etc, the security/validity kernel should be trustable and consistent.

**Comment by fkiraly** [comment]
From a "measure" architectural perspective, I guess the interesting question is this: there are some evaluation measures/modalities in which you compute tables, curves, etc, and then might report summaries, or visualize the more granular data.

Example: ROC (= sens/spec = TPR/FPR), or prec/recall (=TPR/PPV) - the curve itself - versus the area under it, or some statistic associated to an optimum.

Much of this is no longer, strictly speaking, a measure that allows direct comparison. Certainly, you can look at "is sensitivity higher", but for an element of the ROC, or even the entire curve, there is no natural point of comparison.

Thus, it seems some outputs are more naturally post-hoc-analyses than measures?

**Comment by fkiraly** [comment]
Regarding computation: currently, the confusion_matrix architecture seems to just call single binary measures, e.g., `fnr_cm`, rather than compute all than can be computed easily in one batch (e.g., the entire confusion table).

For confusion matrix, it's not such an efficiency loss, but for curves such as in the survival or probabilistic classification setting, it might be.

Any good reason why it needs to be this way?

**Comment by RaphaelS1** [comment]
My suggestion then is:

- Use survAUC for now and note it's problems
- Re-write our own metrics for the ones currently dependent on survAUC.

In general (and I am aware there might be opposition here) but regarding implementation I have found that when vectorization via matrices is possible, R performance is usually as good, if not better, than C, otherwise C for anything involving loops (often necessary for concordance measures). My point here being that whilst the losses in survAUC are fairly transparent, I think a discussion regarding transparency and implementation of the code would be beneficial before our own implementation.

**Comment by RaphaelS1** [comment]
And in response to @fkiraly point about granular measures. I'd also add that for measures such as sensitive and specificity, there is also an added layer of complexity by determining the type of TPR, i.e. cumulative or incidence, which is only made more complex by then make the user choose an lp threshold (which is not obvious). So I don't necessarily think TPR or TNR are required as separate measures and AUCs should suffice.

**Comment by RaphaelS1** [comment]
And in response to @fkiraly point about granular measures. I'd also add that for measures such as sensitive and specificity, there is also an added layer of complexity by determining the type of TPR, i.e. cumulative or incidence, which is only made more complex by then make the user choose an lp threshold (which is not obvious). So I don't necessarily think TPR or TNR are required as separate measures and AUCs should suffice.

**Comment by mllg** [comment]
> Regarding computation: currently, the confusion_matrix architecture seems to just call single binary measures, e.g., `fnr_cm`, rather than compute all than can be computed easily in one batch (e.g., the entire confusion table).
> 
> For confusion matrix, it's not such an efficiency loss, but for curves such as in the survival or probabilistic classification setting, it might be.
> 
> Any good reason why it needs to be this way?

No, not really.

I just wanted to keep the maintenance low and avoid implementing measures in two places. And as you already noted, the efficiency loss here is negligible. The expensive part is calculating the confusion matrix: this scales with `n`, maybe `n^2`, I did not check the implementation of `table()`. The measures can then usually be calculated in a second step in constant time.
