### ISSUE TITLE
!!! Windows Error!

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#50]
I can't find the problem anywhere and only occurs on winbuilder. Error and warning:

```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! Package inputenc Error: Unicode char ‐ (U+2010)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
* checking PDF version of manual without hyperrefs or index ... ERROR
```

Manual builds fine on linux and osx, does anyone have any advice about how to find where  (U+2010) is being used instead of just `-` (I think that's the error anyway)

**Comment by jakob-r** [comment]
Just search for the regex `\x{2010}`. It will give you this line: https://github.com/mlr-org/mlr3proba/blob/a0e5a3fbd8807a2cfe0495a159d58b12b310180a/R/LearnerSurvCoxPH.R#L10

**Comment by RaphaelS1** [comment]
Thank you!!! I was doing a search for anything non-ASCII, was taking a very long time. I will save that snippet for next time!

**Comment by RaphaelS1** [comment]
BTW do you know what mlr3 uses for windows CI ?
