### ISSUE TITLE
Add different choice of integration approximations for integrated scores

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#52]
Currently IGS and ILL are implemented with a single approximation method, which takes the sample mean over unique time-points. For discrete learners this approximation is fine however for continuous learners, better options are available (e.g. random grid of many points). Therefore more choices for approximation should be added for better flexibility and transparency.

**Comment by RaphaelS1** [comment]
See #56

**Comment by fkiraly** [comment]
Perhaps a subsidiary point, arising from #56 where @RaphaelS1 notes that outputs from `pec` IBS/RPS and Graf's version don't agree: I believe these are different approximations of the same approximand. So a weaker version of the sanity check from which #56 has arison would be to check whether the values from the two scores are similar (not idendical) if the test set is large.

**Comment by RaphaelS1** [comment]
I have done checks similar to this for the currently implemented methods, but agree this should be done for all future implementations
