### ISSUE TITLE
surv.parametric, add warnings for possibly incompatible distribution forms?

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#54]
See #49 for full discussion. Opening this issue to ensure all conversation about it in one place

**Comment by fkiraly** [comment]
What I meant: how are the values for `mean` and `sd` determined by the `lp`-evaluate?
Or are they just the defaults, i.e., 0 and 1?

**Comment by RaphaelS1** [comment]
As I don't think `lp` is related to the location-scale parameters (though I could be misunderstanding the maths) but I think the location/scale params are fit via (full) MLE assuming an AFT form. These fitted parameters and coefficients are then used to derive `lp`

**Comment by fkiraly** [comment]
Well, you say `S(t) = S0(t)^exp(lp))`, but here S0 depends on the mean and variance of the predictive distribution. If you say these are fitted, then in which part of the code does this happen?

**Comment by RaphaelS1** [comment]
In `train`, the coefficients of the model `B`, and the parameters of the baseline `S0` are fit, both using MLE at the same time (I think**) - will find a reference

**Comment by RaphaelS1** [comment]
Okay, copying from Modelling Survival Data in Medical Research: The AFT model is fit with the full likelihood:

L(alpha, mu, sigma) = \Prod^n_i=1 (sigma*t_i)^(-delta_i) {f_eps_i(z_i)}^delta_i {S_eps_i(z_i)}^(1-delta_i)

Where alpha are the coefficients to be fitted, mu is the location parameter, and sigma is the scale parameter

**Comment by RaphaelS1** [comment]
So in essence in `surv.parametric` we are maximising the above likelihood w.r.t. alpha, mu, and sigma. Then taking the estimates for mu and sigma and casting these into a distr6 compatible framework. Deriving a linear predictor using `alphaX` where `X` is new data, then combining these using a linear model form, e.g. `S(t) = S0(t)^exp(lp))`

where S0 ~ F_mu,sigma and lp = `alphaX`

**Comment by RaphaelS1** [comment]
Now I think that this is identical to the PH case, the problem is then one of interpretation and not whether mathematically possible. It is just meaningless to have a PH model with Gaussian baseline hazard as the Gaussian hazard does not have the PH property

**Comment by fkiraly** [comment]
ah, I see - so we have abstract functionality to MLE estimate parameters of any parametric distr distribution? I didn't know that existed - where is that?

Indenendently of this remark, if this is the case, it is well-specified, but maybe has to be said in the documentation. Without saying how the parameters of S0 are estimated, the description is incomplete.

**Comment by fkiraly** [comment]
Reagarding the PH model: there's perhaps a misunderstanding or miscommunication here?

In-principle, you can use *any* unconditional distr estimate as the baseline hazard. Some are a bit strange if they allow negative numbers to appear, but not necessarily wrong, depending on context. If you want non-negative outcomes, you can always truncate left at zero.

**Comment by RaphaelS1** [comment]
Let's discuss some Tuesday when we have more time and details. I need to properly read through the `survival::survreg` code. This is very low priority (i.e. post-Feb)

**Comment by fkiraly** [comment]
Just looked at the code
https://github.com/mlr-org/mlr3proba/blob/master/R/LearnerSurvParametric.R
line 86 and 87 is getting `coefficients[1]` and `scale` from the `survreg` `fit` return object, where `survreg` accepts six distributions by default and produces these. You plug them into respective distr6 return objects then

Now I'm not sure whether the implied distirbutions are always correctly obtained by plugging these in as location/scale of the baseline distr, but indeed what you say seems to be true, i.e., that however this is encoded, it should be an MLE fit.

**Comment by fkiraly** [comment]
>This is very low priority

Agreed, because you are *interfacing* `survreg`, which is a widely used and well-tested piece of functionality. The most likely failure point seems getting the parameters out of the return object, and plugging them in correctly.
