### ISSUE TITLE
Add oblique random survival forests

### ISSUE THREAD

**Issue by adibender** [mlr-org/mlr3proba#55]
https://cran.r-project.org/web/packages/obliqueRSF/

**Comment by fkiraly** [comment]
should this not go in the wish list issue #34?

**Comment by fkiraly** [comment]
ah, that's only prob. regression. Should we open a wishlist for survival models?
Or is the mlr3 convention to have one issue per wish?

**Comment by RaphaelS1** [comment]
No, this isn't a loss, and I think that specific models to implement should be in separate issues to make it easier to open and close issues

**Comment by RaphaelS1** [comment]
> Should we open a wishlist for survival models?

As above I think it better to have one per model

**Comment by fkiraly** [comment]
Silly me, I linked the losses list and not the prob. learner list. But in fact this is neither.
On a similar note, should I re-factor the other lists into individual issues?

**Comment by fkiraly** [comment]
Just deleted my confused and unhelpful posts.

**Comment by fkiraly** [comment]
Um, now that I have deleted my posts, your reply, @RaphaelS1, looks like it is a particularly strange reply to the original post. Not sure what to do about this...
I don't feel very helpful now.
