### ISSUE TITLE
mlr::tsk() not found

### ISSUE THREAD

**Issue by juliopterix** [mlr-org/mlr3proba#65]
Hi,

I just tried to follow the first example given at https://mlr3book.mlr-org.com/survival.html#survival : 
`library(mlr3proba)`
`task = tsk("rats")`

However, tsk() cannot be found.

I tried both `install.packages("mlr3proba")` and `remotes::install_github("mlr-org/mlr3proba")`

Best
Julius

**Comment by RaphaelS1** [comment]
Hi can you retry by first running `library(mlr3)`

I'll add this to the book

**Comment by juliopterix** [comment]
ah yes great, thanks!
