### ISSUE TITLE
Consider adding a fourth PredictionSurv predict type: time?

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#70]
There are some learners that can be used to predict survival time. For example, the AFT linear predictor is equal to logT, so we could return a survival time with the simple transformation exp(lp). This would not require any subjective composition. The advantage of doing so, would be to increase the amount of possible returned information, and to enable measures that can compare distance between predicted survival times, e.g. censoring adjusted RMSE, and MAE. It could also help make clearer distinctions between the different SVM methods.

**Comment by fkiraly** [comment]
I was just going to ask "how is this different from `response`" but I saw in `PredictionSurv` that this doesn't actually exist. I'm surprised I didn't notice that.

As without censoring, survival should be identical with regression, so I'd say, yes, makes sense. Though it makes sense to call the return types the same, so it should be called `response` like in the deterministic classification/regression case.

**Comment by fkiraly** [comment]
We may also consider adding `se` in this case, btw.

It's interesting to ask what the default should be. Expected conditional label is more standard in prob.reg, while in survival it's probably median survival? Though we already have the latter as standard for crank if I'm not mistaken?

**Comment by fkiraly** [comment]
On the other hand, I'm wondering: are we slowly adding all the `distr6` slots as return types? I.e., is this feature creep, or a good idea?

**Comment by RaphaelS1** [comment]
> I was just going to ask "how is this different from response" but I saw in PredictionSurv that this doesn't actually exist. I'm surprised I didn't notice that.

Sure `response` makes sense, bearing in mind the vast majority of learners will not return this.

> We may also consider adding se in this case, btw.

I'm unsure how `se` is returned from these learners but, as you just said, this can be returned by the `se` of the distribution using `distr6`, so might be repeated. 

> It's interesting to ask what the default should be. Expected conditional label is more standard in prob.reg, while in survival it's probably median survival? Though we already have the latter as standard for crank if I'm not mistaken?

Default is mean. Because a) can be quickly for `WeightedDiscrete` , b) median can be misleading as many baseline estimators never reach 0.5

**Comment by fkiraly** [comment]
> b) median can be misleading as many baseline estimators never reach 0.5

Really, how so? 
Dont' all distr6 real distributions have at least a well-defined `cdf` and `icdf`, and you could call `icdf(0.5)`?

**Comment by RaphaelS1** [comment]
> Dont' all distr6 real distributions have at least a well-defined cdf and icdf, and you could call icdf(0.5)?

By example:

```R
lrn = lrn("surv.kaplan")
tsk = tsk("rats")
p = lrn$train(tsk)$predict(tsk)
d = p$distr[1]
plot(d, "survival")
d$quantile(0.5)
```

There are many cases where the KM estimate never reaches the 0.5 proportion, which means that the median is returned as the last point in the support

**Comment by fkiraly** [comment]
oh - this is an "improper" distribution then!

I didn't consider this on my mental radar, but indeed KM estimates may be survival curves that never reach zero.
Have we carefully thought about how this interacts with the distr6 interface? 
Since in some compositors we may be assuming that F(infinity) = 1.

**Comment by adibender** [comment]
> I didn't consider this on my mental radar, but indeed KM estimates may be survival curves that never reach zero.

Isn't that true for all empiricall/estimated survival curves?

**Comment by RaphaelS1** [comment]
> Have we carefully thought about how this interacts with the distr6 interface?
Since in some compositors we may be assuming that F(infinity) = 1.

I think the key point is that survival curves are discrete and only exist on the support of observed death times. Therefore at time 0 `S(t) = 1 -> F(t) = 0` and any time after the final death time, `S(t) = 0 -> F(t) = 1`.  These results are guaranteed by the distr6 interface which internally set F(t) = 0, for t before support and F(t) = 1, for t after support; for all distributions.

> Isn't that true for all empirical/estimated survival curves?

I think if the final event time, t_i, is a death then for Kaplan-Meier: d_i = 1, n_i = 1, and so (1-d_i/n_i) = 0
But it's just very rare in the real-world that the final event time is death not censoring.

**Comment by fkiraly** [comment]
>Isn't that true for all empirical/estimated survival curves?

No? For example, it´s not true for the estimate that says everyone dies at t=0.

Even in the case of KM, you sometimes get a "proper" distribution, sometimes not - the former happens iff one of the produce terms is zero, i.e., if the last people you observe dying are exactly the people who were still observed at that point.

>I think the key point is that survival curves are discrete and only exist on the support of observed death times. 

You probably mean that the estimated survival curves correspond to distributions supported only on the observed death time.
This is only true for KM estimators or related estimators - it is perfectly possible to write down estimators that produce absolutely continuous distributions, i.e., without a discrete part.

>These results are guaranteed by the distr6 interface which internally set F(t) = 0, for t before support and F(t) = 1, for t after support

This is what I meant with "interactions"! If you were strict, F(t) would plateau out at some number strictly smaller than 1 for the F coming from the KM estimator!
But by the distr6 convention, you assume it´s a "proper" distribution, hence you make it plateau out at 1.

>I think if the final event time, t_i, is a death then for Kaplan-Meier: d_i = 1, n_i = 1, and so (1-d_i/n_i) = 0
>But it's just very rare in the real-world that the final event time is death not censoring.

Correct, hence the problem is not a rare case but in fact a typical case.

**Comment by adibender** [comment]
> > Isn't that true for all empirical/estimated survival curves?
> 
> No? For example, it´s not true for the estimate that says everyone dies at t=0.

Sorry, I wasn't very precise. What I meant to say was that for  all (non-/semi-parametric) methods, not only KM, it could be true that the conditional survival curve will not reach zero (within the range of observed event times).

> Thus, the problem is not a rare case but in fact a typical case.

Exactly. And beyond the univariate KM case, this could be true for one set of covariates but not another. In a stratified model for example, survival curve might reach zero for one group, but not the other.

**Comment by RaphaelS1** [comment]
I'm happy to keep discussing this but this issue was actually closed in c6fcc2e70977190c63213bcc106e4aa8911e7a93. Is our conversation here worth moving to a new issue before I close this one?

**Comment by adibender** [comment]
Just for clarification (otherwise can be closed I think): 
- the learner only returns predict type `response` if the underlying package/function supports it?
- do we have learners implemented that would have to be adjusted because of this change?

**Comment by RaphaelS1** [comment]
That is correct. Currently I am only aware of two learners that can do this: `surv.parametric` but only if AFT type is used, and `surv.svm` but only if model 2 (I think that's the one) is used.

**Comment by RaphaelS1** [comment]
And if only `response` is returned (no `lp` or `distr`) then `crank = response`
