### ISSUE TITLE
Consider abstraction of measures

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#72]
There are currently 21 measures in mlr3proba, 6 of these are implemented in this package, 14 are in `survAUC` (which we want to re-implement), and another 6 are being added in an upcoming PR for response predict types. These will only continue to grow as we add density estimation and probabilistic regression. Before this package becomes too buried in measures, it may be time to consider:

a) Moving losses implemented here to:
1. `mlr3measures`
2. PR to `metrics`
3. Our own `metricsProba`

b) Moving measure classes to `mlr3measures`

**Comment by fkiraly** [comment]
Hm if we re-factor, `mlr3measures` sounds like a good place currently.

Why: due to mlr3 API design, there is a distinction between
"loss function X for task Y"
and "loss function X".
For example, the log-loss for continuous real distributions is the same for survival, probabilistic supervised regression, density estimation, probabilistic forecasting. However, this needs to be four metrics objects since dispatch is not by return type but by task.

(which I´m slightly unhappy about, so wonder whether there is room for re-factor/re-design, @mllg ?)

Another question to consider is the `distr6` dependency: it would be introduced wherever we put them. So it may depends on the question of whether it will become an mlr3 dependency after a re-factor of regression/classification return types - or not.

Due to this, `metrics` is probably out of the question.

**Comment by mllg** [comment]
> Hm if we re-factor, `mlr3measures` sounds like a good place currently.

:+1:

I've tried to PR changes into Metrics, but did not get any responses in a timely manner. This is why I created `mlr3measures`. I also tried to avoid any unnecessary dependencies, so this package can be used without the mlr3verse.



> Why: due to mlr3 API design, there is a distinction between
> "loss function X for task Y"
> and "loss function X".
> For example, the log-loss for continuous real distributions is the same for survival, probabilistic supervised regression, density estimation, probabilistic forecasting. However, this needs to be four metrics objects since dispatch is not by return type but by task.

The decision to have task-specific measures was probably too hasty, and should be reconsidered. @pfistfl also reported that things are ugly now in the forecast package.

I'll have a closer look this week if a redesign is possible.



> Another question to consider is the `distr6` dependency: it would be introduced wherever we put them. So it may depend on the question of whether it will become an mlr3 dependency after a re-factor of regression/classification return types - or not.

For `mlr3measures` this could also go into suggests?

**Comment by RaphaelS1** [comment]
> The decision to have task-specific measures was probably too hasty, and should be reconsidered. @pfistfl also reported that things are ugly now in the forecast package.
I'll have a closer look this week if a redesign is possible.

I think a redesign could be nice if possible but it is quite nice to be able to know that (for example) `surv.logloss` is a version of the logloss that accounts for censoring and `dens.logloss` does not have this problem. They do have to be coded differently and the user then intuitively knows what is being used as opposed to just `logloss`. Although I appreciate that we could keep the `msr("surv.logloss")` constructor and internally these all just call a variant of a single measure.

> For mlr3measures this could also go into suggests?

Yes it would be for `mlr3measures`. But I've found that although `distr6` could technically be a suggest in `mlr3proba`, it is needed in every class so it was just much easier to import the whole package

**Comment by mllg** [comment]
> I think a redesign could be nice if possible but it is quite nice to be able to know that (for example) `surv.logloss` is a version of the logloss that accounts for censoring and `dens.logloss` does not have this problem. They do have to be coded differently and the user then intuitively knows what is being used as opposed to just `logloss`. Although I appreciate that we could keep the `msr("surv.logloss")` constructor and internally these all just call a variant of a single measure.


So what do you propose? Stick with the current design and just create duplicated measures to account for multiple tasks?

**Comment by RaphaelS1** [comment]
I think stick with current design but try and make sure that duplicated measures aren't created.
e.g. for logloss:

classif.logloss
surv.logloss
dens.logloss
regr.logloss

Where all four are defined as `-log(p(y))` so `mlr3measures` however `classif` doesn't use a `distr` return type, `surv` requires accounting for censoring, and `dens` and `regr` are identical. 

So my opinion is have one implementation of `logloss` in `mlr3measures`, four different measures as above, corresponding to the task, and these internally make adjustments before calling `logloss` from `mlr3measures`. Multiple measure objects in `mlr3verse` but one measure definition in `mlr3measures`.

**Comment by fkiraly** [comment]
Perhaps the "obvious" alternative is to have output specific classes that follow closely the mathematical type of what is a "loss", namely just based on predict and observation type - and then wrappers to or dispatch from task interface.

E.g., have *one* `logloss.reals` for the one over the real numbers, and this can be used whenever the output type comparison is "absolutely continuous distribution over the reals, with a real number" - that is, in probabilistic supervised regression, density estimation, probabilistic forecasting of a continuous quantity, and so on.

The trade-off seems between interface complexity (possibly over-engineering it) and instance complexity (possibly under-abstracting it).

**Comment by fkiraly** [comment]
PS: I *do* consider the survival log-loss different from regression log-loss, because it is a *different mathematical object*, so a distinction in either case may be sensible. 
Whereas the "density estimation log-loss" is not different from the "regression log-loss", *as a mathematical object*, so I feel the distinction is counterintuitive and possibly unnecessary.
