### ISSUE TITLE
with_package not imported

### ISSUE THREAD

**Issue by adibender** [mlr-org/mlr3proba#73]
I noticed that `with_package` was introduced for **`mboost`** related functions, however, the **`withr`** package is not imported, nor is the `with_package` function, which breaks tests. 

I can make a PR that fixes this, but wanted to make sure that `with_package` is really necessary (what is special about mboost?), because it means introducing another dependency. 

Another Q is whether to put it into imports or suggests?

**Comment by RaphaelS1** [comment]
It shouldn't break anything, we are using @mllg version in mlr3misc ` mlr3misc::with_package` Where is it breaking?

**Comment by adibender** [comment]
hm strange, I got errors, when running tests locally. Will investigate further

**Comment by adibender** [comment]
hm, appears I had **`mlr3misc_0.1.6`**, while **`mlr3misc_0.1.7`** is required.
