### ISSUE TITLE
Add integrated AUC measure

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#8]

**Comment by fkiraly** [comment]
short question: which curve are you referring to?
The one that you get when you increase time, and look at roc of "dead/alive"?

**Comment by RaphaelS1** [comment]
See:

Heagerty, Lumley and Pepe (2000) _Time-Dependent ROC Curves for Censored Survival Data and a Diagnostic Marker_

**Comment by fkiraly** [comment]
If I read the paper correctly, from predicted survival distributions you get one (sensitivity/speifity) ROC curve per cut-off time, by reduction to classification (by binning).
Thus, you have one auROC per cut-off time point, which is hence the same as the auROC for the implied classifier.
So, computing the integrated auROC is just a matter of repeated, thresholded binning to reduce to classification, then compute the auROC for each of the reductions, then sum/integrate. Not sure whether it can be done more efficiently than the naive way.

As a measure of goodness, a bit strange, but if we really insist on having this...

**Comment by RaphaelS1** [comment]
The package `survAUC` implements variants of the time-dependent AUROC as well as unbiased c-index. I need to check how well these are implemented though

**Comment by RaphaelS1** [comment]
Generalised in #16
