### ISSUE TITLE
Document risk to prob conversion in all learners

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#9]
This is high priority before publication as documentation for survival predictions are confused across multiple packages. There are two things to make clear in every learner:

1. What is the predicted "risk"?
2. How is this 'risk' (when predicted) used to create a survival probability?

Where possible the composition methods should be open to choice by the user via a parameter set. For example in glmnet, we include the additional parameter "basehaz.estimator" which allows the user to select either the Kaplan-Meier or Nelson-Aalen estimator for the baseline hazard. However in some models, e.g. rpart, this is a more complex procedure that should be explained.

**Comment by fkiraly** [comment]
@mllg, I've looked at the existing solutions (not pointing fingers) with @RaphaelS1 - I think there is a general theme of obscure coding, faulty implementation, non-explicit approximation going on.

These are, in my opinion, no-gos for the "evaluation/validation" part of a workflow. I'd suggest to use transparent scorer functions instead, e.g., implementing proper losses or easy-to-check aggregates that don't make arcane approximations.

**Comment by mllg** [comment]
> I think there is a general theme of obscure coding, faulty implementation, non-explicit approximation going on

I had a very similar impression. 



> These are, in my opinion, no-gos for the "evaluation/validation" part of a workflow, since it needs to be reliable not only in terms of functionality but also in terms of argumentation and inspectability.
> I'd hence suggest to use transparent scorer functions instead, e.g., implementing proper losses or easy-to-check aggregates that don't make arcane approximations.

This would be a huge step for survival analysis in R. Let me know how I can help out.

**Comment by RaphaelS1** [comment]
> This would be a huge step for survival analysis in R. Let me know how I can help out.

I think for now we are happy to keep adding these in mlr3proba but we may want to consider in the future abstracting to either a `MetricsPro` package or `mlr3evaluation`
